// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ActivationForecast struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// `measured` from this profile's own workers on this path, `estimated`from the profile's registered cold-start estimate, or `unknown`.
	basis *string
	// How long the pending worker has been starting, when one is visible.
	elapsed_ms *int64
	// Median and p95 time still to go, never negative. Null when nothing isknown; a router must then fall back to its default poll.
	expected_remaining_ms *int64
	// Median start-to-ready on this path, from scheduling to Ready.
	expected_total_ms *int64
	// The p95_remaining_ms property
	p95_remaining_ms *int64
	// The p95_total_ms property
	p95_total_ms *int64
	// `restore` or `cold`: the path the pending worker is (or will be) on.
	path *string
	// How the path was decided: `pod` (the pending pod carries a checkpointpath, or does not), `artifact` (no pod yet, but a ready checkpointexists for this profile's compatibility key), or `none` (no pod, noartifact — a cold start is the only thing that can happen).
	path_basis *string
	// The samples property
	samples *int64
}

// NewActivationForecast instantiates a new ActivationForecast and sets the default values.
func NewActivationForecast() *ActivationForecast {
	m := &ActivationForecast{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateActivationForecastFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateActivationForecastFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewActivationForecast(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ActivationForecast) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetBasis gets the basis property value. `measured` from this profile's own workers on this path, `estimated`from the profile's registered cold-start estimate, or `unknown`.
// returns a *string when successful
func (m *ActivationForecast) GetBasis() *string {
	return m.basis
}

// GetElapsedMs gets the elapsed_ms property value. How long the pending worker has been starting, when one is visible.
// returns a *int64 when successful
func (m *ActivationForecast) GetElapsedMs() *int64 {
	return m.elapsed_ms
}

// GetExpectedRemainingMs gets the expected_remaining_ms property value. Median and p95 time still to go, never negative. Null when nothing isknown; a router must then fall back to its default poll.
// returns a *int64 when successful
func (m *ActivationForecast) GetExpectedRemainingMs() *int64 {
	return m.expected_remaining_ms
}

// GetExpectedTotalMs gets the expected_total_ms property value. Median start-to-ready on this path, from scheduling to Ready.
// returns a *int64 when successful
func (m *ActivationForecast) GetExpectedTotalMs() *int64 {
	return m.expected_total_ms
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *ActivationForecast) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["basis"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetBasis(val)
		}
		return nil
	}
	res["elapsed_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetElapsedMs(val)
		}
		return nil
	}
	res["expected_remaining_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetExpectedRemainingMs(val)
		}
		return nil
	}
	res["expected_total_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetExpectedTotalMs(val)
		}
		return nil
	}
	res["p95_remaining_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetP95RemainingMs(val)
		}
		return nil
	}
	res["p95_total_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetP95TotalMs(val)
		}
		return nil
	}
	res["path"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPath(val)
		}
		return nil
	}
	res["path_basis"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPathBasis(val)
		}
		return nil
	}
	res["samples"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSamples(val)
		}
		return nil
	}
	return res
}

// GetP95RemainingMs gets the p95_remaining_ms property value. The p95_remaining_ms property
// returns a *int64 when successful
func (m *ActivationForecast) GetP95RemainingMs() *int64 {
	return m.p95_remaining_ms
}

// GetP95TotalMs gets the p95_total_ms property value. The p95_total_ms property
// returns a *int64 when successful
func (m *ActivationForecast) GetP95TotalMs() *int64 {
	return m.p95_total_ms
}

// GetPath gets the path property value. `restore` or `cold`: the path the pending worker is (or will be) on.
// returns a *string when successful
func (m *ActivationForecast) GetPath() *string {
	return m.path
}

// GetPathBasis gets the path_basis property value. How the path was decided: `pod` (the pending pod carries a checkpointpath, or does not), `artifact` (no pod yet, but a ready checkpointexists for this profile's compatibility key), or `none` (no pod, noartifact — a cold start is the only thing that can happen).
// returns a *string when successful
func (m *ActivationForecast) GetPathBasis() *string {
	return m.path_basis
}

// GetSamples gets the samples property value. The samples property
// returns a *int64 when successful
func (m *ActivationForecast) GetSamples() *int64 {
	return m.samples
}

// Serialize serializes information the current object
func (m *ActivationForecast) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("basis", m.GetBasis())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("elapsed_ms", m.GetElapsedMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("expected_remaining_ms", m.GetExpectedRemainingMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("expected_total_ms", m.GetExpectedTotalMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("p95_remaining_ms", m.GetP95RemainingMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("p95_total_ms", m.GetP95TotalMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("path", m.GetPath())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("path_basis", m.GetPathBasis())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("samples", m.GetSamples())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ActivationForecast) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetBasis sets the basis property value. `measured` from this profile's own workers on this path, `estimated`from the profile's registered cold-start estimate, or `unknown`.
func (m *ActivationForecast) SetBasis(value *string) {
	m.basis = value
}

// SetElapsedMs sets the elapsed_ms property value. How long the pending worker has been starting, when one is visible.
func (m *ActivationForecast) SetElapsedMs(value *int64) {
	m.elapsed_ms = value
}

// SetExpectedRemainingMs sets the expected_remaining_ms property value. Median and p95 time still to go, never negative. Null when nothing isknown; a router must then fall back to its default poll.
func (m *ActivationForecast) SetExpectedRemainingMs(value *int64) {
	m.expected_remaining_ms = value
}

// SetExpectedTotalMs sets the expected_total_ms property value. Median start-to-ready on this path, from scheduling to Ready.
func (m *ActivationForecast) SetExpectedTotalMs(value *int64) {
	m.expected_total_ms = value
}

// SetP95RemainingMs sets the p95_remaining_ms property value. The p95_remaining_ms property
func (m *ActivationForecast) SetP95RemainingMs(value *int64) {
	m.p95_remaining_ms = value
}

// SetP95TotalMs sets the p95_total_ms property value. The p95_total_ms property
func (m *ActivationForecast) SetP95TotalMs(value *int64) {
	m.p95_total_ms = value
}

// SetPath sets the path property value. `restore` or `cold`: the path the pending worker is (or will be) on.
func (m *ActivationForecast) SetPath(value *string) {
	m.path = value
}

// SetPathBasis sets the path_basis property value. How the path was decided: `pod` (the pending pod carries a checkpointpath, or does not), `artifact` (no pod yet, but a ready checkpointexists for this profile's compatibility key), or `none` (no pod, noartifact — a cold start is the only thing that can happen).
func (m *ActivationForecast) SetPathBasis(value *string) {
	m.path_basis = value
}

// SetSamples sets the samples property value. The samples property
func (m *ActivationForecast) SetSamples(value *int64) {
	m.samples = value
}

type ActivationForecastable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetBasis() *string
	GetElapsedMs() *int64
	GetExpectedRemainingMs() *int64
	GetExpectedTotalMs() *int64
	GetP95RemainingMs() *int64
	GetP95TotalMs() *int64
	GetPath() *string
	GetPathBasis() *string
	GetSamples() *int64
	SetBasis(value *string)
	SetElapsedMs(value *int64)
	SetExpectedRemainingMs(value *int64)
	SetExpectedTotalMs(value *int64)
	SetP95RemainingMs(value *int64)
	SetP95TotalMs(value *int64)
	SetPath(value *string)
	SetPathBasis(value *string)
	SetSamples(value *int64)
}
