// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// CpuInfo cPU of one node.
type CpuInfo struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// CPUs the scheduler can hand out, after system reservations
	allocatable_cores *float64
	// "amd64" or "arm64"
	architecture *string
	// Logical CPUs on the node
	cores *float64
	// Whether SMT/hyper-threading is on (Node Feature Discovery)
	hyperthreading *bool
	// Hypervisor the node runs under, e.g. "kvm"; newer NFD versions only
	hypervisor *string
	// Highest x86-64 microarchitecture level, e.g. "x86-64-v4" (Node Feature Discovery)
	isa_level *string
	// "Intel" or "AMD" (Node Feature Discovery)
	vendorEscaped *string
	// Whether the node is a VM, from the CPUID hypervisor flag (Node Feature Discovery)
	virtualized *bool
}

// NewCpuInfo instantiates a new CpuInfo and sets the default values.
func NewCpuInfo() *CpuInfo {
	m := &CpuInfo{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateCpuInfoFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCpuInfoFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewCpuInfo(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CpuInfo) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAllocatableCores gets the allocatable_cores property value. CPUs the scheduler can hand out, after system reservations
// returns a *float64 when successful
func (m *CpuInfo) GetAllocatableCores() *float64 {
	return m.allocatable_cores
}

// GetArchitecture gets the architecture property value. "amd64" or "arm64"
// returns a *string when successful
func (m *CpuInfo) GetArchitecture() *string {
	return m.architecture
}

// GetCores gets the cores property value. Logical CPUs on the node
// returns a *float64 when successful
func (m *CpuInfo) GetCores() *float64 {
	return m.cores
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *CpuInfo) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["allocatable_cores"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAllocatableCores(val)
		}
		return nil
	}
	res["architecture"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetArchitecture(val)
		}
		return nil
	}
	res["cores"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCores(val)
		}
		return nil
	}
	res["hyperthreading"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetHyperthreading(val)
		}
		return nil
	}
	res["hypervisor"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetHypervisor(val)
		}
		return nil
	}
	res["isa_level"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIsaLevel(val)
		}
		return nil
	}
	res["vendor"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetVendorEscaped(val)
		}
		return nil
	}
	res["virtualized"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetVirtualized(val)
		}
		return nil
	}
	return res
}

// GetHyperthreading gets the hyperthreading property value. Whether SMT/hyper-threading is on (Node Feature Discovery)
// returns a *bool when successful
func (m *CpuInfo) GetHyperthreading() *bool {
	return m.hyperthreading
}

// GetHypervisor gets the hypervisor property value. Hypervisor the node runs under, e.g. "kvm"; newer NFD versions only
// returns a *string when successful
func (m *CpuInfo) GetHypervisor() *string {
	return m.hypervisor
}

// GetIsaLevel gets the isa_level property value. Highest x86-64 microarchitecture level, e.g. "x86-64-v4" (Node Feature Discovery)
// returns a *string when successful
func (m *CpuInfo) GetIsaLevel() *string {
	return m.isa_level
}

// GetVendorEscaped gets the vendor property value. "Intel" or "AMD" (Node Feature Discovery)
// returns a *string when successful
func (m *CpuInfo) GetVendorEscaped() *string {
	return m.vendorEscaped
}

// GetVirtualized gets the virtualized property value. Whether the node is a VM, from the CPUID hypervisor flag (Node Feature Discovery)
// returns a *bool when successful
func (m *CpuInfo) GetVirtualized() *bool {
	return m.virtualized
}

// Serialize serializes information the current object
func (m *CpuInfo) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteFloat64Value("allocatable_cores", m.GetAllocatableCores())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("architecture", m.GetArchitecture())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("cores", m.GetCores())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("hyperthreading", m.GetHyperthreading())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("hypervisor", m.GetHypervisor())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("isa_level", m.GetIsaLevel())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("vendor", m.GetVendorEscaped())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("virtualized", m.GetVirtualized())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CpuInfo) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAllocatableCores sets the allocatable_cores property value. CPUs the scheduler can hand out, after system reservations
func (m *CpuInfo) SetAllocatableCores(value *float64) {
	m.allocatable_cores = value
}

// SetArchitecture sets the architecture property value. "amd64" or "arm64"
func (m *CpuInfo) SetArchitecture(value *string) {
	m.architecture = value
}

// SetCores sets the cores property value. Logical CPUs on the node
func (m *CpuInfo) SetCores(value *float64) {
	m.cores = value
}

// SetHyperthreading sets the hyperthreading property value. Whether SMT/hyper-threading is on (Node Feature Discovery)
func (m *CpuInfo) SetHyperthreading(value *bool) {
	m.hyperthreading = value
}

// SetHypervisor sets the hypervisor property value. Hypervisor the node runs under, e.g. "kvm"; newer NFD versions only
func (m *CpuInfo) SetHypervisor(value *string) {
	m.hypervisor = value
}

// SetIsaLevel sets the isa_level property value. Highest x86-64 microarchitecture level, e.g. "x86-64-v4" (Node Feature Discovery)
func (m *CpuInfo) SetIsaLevel(value *string) {
	m.isa_level = value
}

// SetVendorEscaped sets the vendor property value. "Intel" or "AMD" (Node Feature Discovery)
func (m *CpuInfo) SetVendorEscaped(value *string) {
	m.vendorEscaped = value
}

// SetVirtualized sets the virtualized property value. Whether the node is a VM, from the CPUID hypervisor flag (Node Feature Discovery)
func (m *CpuInfo) SetVirtualized(value *bool) {
	m.virtualized = value
}

type CpuInfoable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAllocatableCores() *float64
	GetArchitecture() *string
	GetCores() *float64
	GetHyperthreading() *bool
	GetHypervisor() *string
	GetIsaLevel() *string
	GetVendorEscaped() *string
	GetVirtualized() *bool
	SetAllocatableCores(value *float64)
	SetArchitecture(value *string)
	SetCores(value *float64)
	SetHyperthreading(value *bool)
	SetHypervisor(value *string)
	SetIsaLevel(value *string)
	SetVendorEscaped(value *string)
	SetVirtualized(value *bool)
}
