// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CsxNode struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The disk_checkpoints property
	disk_checkpoints *int32
	// The disk_limit_bytes property
	disk_limit_bytes *int64
	// The disk_used_bytes property
	disk_used_bytes *int64
	// The memory_checkpoints property
	memory_checkpoints *int32
	// The memory_limit_bytes property
	memory_limit_bytes *int64
	// Includes copies in flight, which CSX reserves up front.
	memory_used_bytes *int64
	// The node_name property
	node_name *string
	// Last CSX start; the node's caches were empty then.
	started_ms *int64
	// The version property
	version *string
	// Bytes of finished writes still in the tmpfs buffer, waiting to be persisted to NFS.
	write_buffer_bytes *int64
	// The writes_in_flight property
	writes_in_flight *int32
}

// NewCsxNode instantiates a new CsxNode and sets the default values.
func NewCsxNode() *CsxNode {
	m := &CsxNode{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateCsxNodeFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCsxNodeFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewCsxNode(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CsxNode) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetDiskCheckpoints gets the disk_checkpoints property value. The disk_checkpoints property
// returns a *int32 when successful
func (m *CsxNode) GetDiskCheckpoints() *int32 {
	return m.disk_checkpoints
}

// GetDiskLimitBytes gets the disk_limit_bytes property value. The disk_limit_bytes property
// returns a *int64 when successful
func (m *CsxNode) GetDiskLimitBytes() *int64 {
	return m.disk_limit_bytes
}

// GetDiskUsedBytes gets the disk_used_bytes property value. The disk_used_bytes property
// returns a *int64 when successful
func (m *CsxNode) GetDiskUsedBytes() *int64 {
	return m.disk_used_bytes
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *CsxNode) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["disk_checkpoints"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDiskCheckpoints(val)
		}
		return nil
	}
	res["disk_limit_bytes"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDiskLimitBytes(val)
		}
		return nil
	}
	res["disk_used_bytes"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDiskUsedBytes(val)
		}
		return nil
	}
	res["memory_checkpoints"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMemoryCheckpoints(val)
		}
		return nil
	}
	res["memory_limit_bytes"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMemoryLimitBytes(val)
		}
		return nil
	}
	res["memory_used_bytes"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMemoryUsedBytes(val)
		}
		return nil
	}
	res["node_name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNodeName(val)
		}
		return nil
	}
	res["started_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetStartedMs(val)
		}
		return nil
	}
	res["version"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetVersion(val)
		}
		return nil
	}
	res["write_buffer_bytes"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetWriteBufferBytes(val)
		}
		return nil
	}
	res["writes_in_flight"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetWritesInFlight(val)
		}
		return nil
	}
	return res
}

// GetMemoryCheckpoints gets the memory_checkpoints property value. The memory_checkpoints property
// returns a *int32 when successful
func (m *CsxNode) GetMemoryCheckpoints() *int32 {
	return m.memory_checkpoints
}

// GetMemoryLimitBytes gets the memory_limit_bytes property value. The memory_limit_bytes property
// returns a *int64 when successful
func (m *CsxNode) GetMemoryLimitBytes() *int64 {
	return m.memory_limit_bytes
}

// GetMemoryUsedBytes gets the memory_used_bytes property value. Includes copies in flight, which CSX reserves up front.
// returns a *int64 when successful
func (m *CsxNode) GetMemoryUsedBytes() *int64 {
	return m.memory_used_bytes
}

// GetNodeName gets the node_name property value. The node_name property
// returns a *string when successful
func (m *CsxNode) GetNodeName() *string {
	return m.node_name
}

// GetStartedMs gets the started_ms property value. Last CSX start; the node's caches were empty then.
// returns a *int64 when successful
func (m *CsxNode) GetStartedMs() *int64 {
	return m.started_ms
}

// GetVersion gets the version property value. The version property
// returns a *string when successful
func (m *CsxNode) GetVersion() *string {
	return m.version
}

// GetWriteBufferBytes gets the write_buffer_bytes property value. Bytes of finished writes still in the tmpfs buffer, waiting to be persisted to NFS.
// returns a *int64 when successful
func (m *CsxNode) GetWriteBufferBytes() *int64 {
	return m.write_buffer_bytes
}

// GetWritesInFlight gets the writes_in_flight property value. The writes_in_flight property
// returns a *int32 when successful
func (m *CsxNode) GetWritesInFlight() *int32 {
	return m.writes_in_flight
}

// Serialize serializes information the current object
func (m *CsxNode) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt32Value("disk_checkpoints", m.GetDiskCheckpoints())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("disk_limit_bytes", m.GetDiskLimitBytes())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("disk_used_bytes", m.GetDiskUsedBytes())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("memory_checkpoints", m.GetMemoryCheckpoints())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("memory_limit_bytes", m.GetMemoryLimitBytes())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("memory_used_bytes", m.GetMemoryUsedBytes())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("node_name", m.GetNodeName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("started_ms", m.GetStartedMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("version", m.GetVersion())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("writes_in_flight", m.GetWritesInFlight())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("write_buffer_bytes", m.GetWriteBufferBytes())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CsxNode) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetDiskCheckpoints sets the disk_checkpoints property value. The disk_checkpoints property
func (m *CsxNode) SetDiskCheckpoints(value *int32) {
	m.disk_checkpoints = value
}

// SetDiskLimitBytes sets the disk_limit_bytes property value. The disk_limit_bytes property
func (m *CsxNode) SetDiskLimitBytes(value *int64) {
	m.disk_limit_bytes = value
}

// SetDiskUsedBytes sets the disk_used_bytes property value. The disk_used_bytes property
func (m *CsxNode) SetDiskUsedBytes(value *int64) {
	m.disk_used_bytes = value
}

// SetMemoryCheckpoints sets the memory_checkpoints property value. The memory_checkpoints property
func (m *CsxNode) SetMemoryCheckpoints(value *int32) {
	m.memory_checkpoints = value
}

// SetMemoryLimitBytes sets the memory_limit_bytes property value. The memory_limit_bytes property
func (m *CsxNode) SetMemoryLimitBytes(value *int64) {
	m.memory_limit_bytes = value
}

// SetMemoryUsedBytes sets the memory_used_bytes property value. Includes copies in flight, which CSX reserves up front.
func (m *CsxNode) SetMemoryUsedBytes(value *int64) {
	m.memory_used_bytes = value
}

// SetNodeName sets the node_name property value. The node_name property
func (m *CsxNode) SetNodeName(value *string) {
	m.node_name = value
}

// SetStartedMs sets the started_ms property value. Last CSX start; the node's caches were empty then.
func (m *CsxNode) SetStartedMs(value *int64) {
	m.started_ms = value
}

// SetVersion sets the version property value. The version property
func (m *CsxNode) SetVersion(value *string) {
	m.version = value
}

// SetWriteBufferBytes sets the write_buffer_bytes property value. Bytes of finished writes still in the tmpfs buffer, waiting to be persisted to NFS.
func (m *CsxNode) SetWriteBufferBytes(value *int64) {
	m.write_buffer_bytes = value
}

// SetWritesInFlight sets the writes_in_flight property value. The writes_in_flight property
func (m *CsxNode) SetWritesInFlight(value *int32) {
	m.writes_in_flight = value
}

type CsxNodeable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetDiskCheckpoints() *int32
	GetDiskLimitBytes() *int64
	GetDiskUsedBytes() *int64
	GetMemoryCheckpoints() *int32
	GetMemoryLimitBytes() *int64
	GetMemoryUsedBytes() *int64
	GetNodeName() *string
	GetStartedMs() *int64
	GetVersion() *string
	GetWriteBufferBytes() *int64
	GetWritesInFlight() *int32
	SetDiskCheckpoints(value *int32)
	SetDiskLimitBytes(value *int64)
	SetDiskUsedBytes(value *int64)
	SetMemoryCheckpoints(value *int32)
	SetMemoryLimitBytes(value *int64)
	SetMemoryUsedBytes(value *int64)
	SetNodeName(value *string)
	SetStartedMs(value *int64)
	SetVersion(value *string)
	SetWriteBufferBytes(value *int64)
	SetWritesInFlight(value *int32)
}
