// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CsxRead struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The at_ms property
	at_ms *int64
	// The duration_ns property
	duration_ns *int64
	// The node_name property
	node_name *string
	// The tier property
	tier *string
}

// NewCsxRead instantiates a new CsxRead and sets the default values.
func NewCsxRead() *CsxRead {
	m := &CsxRead{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateCsxReadFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCsxReadFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewCsxRead(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CsxRead) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAtMs gets the at_ms property value. The at_ms property
// returns a *int64 when successful
func (m *CsxRead) GetAtMs() *int64 {
	return m.at_ms
}

// GetDurationNs gets the duration_ns property value. The duration_ns property
// returns a *int64 when successful
func (m *CsxRead) GetDurationNs() *int64 {
	return m.duration_ns
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *CsxRead) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["at_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAtMs(val)
		}
		return nil
	}
	res["duration_ns"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDurationNs(val)
		}
		return nil
	}
	res["node_name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNodeName(val)
		}
		return nil
	}
	res["tier"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTier(val)
		}
		return nil
	}
	return res
}

// GetNodeName gets the node_name property value. The node_name property
// returns a *string when successful
func (m *CsxRead) GetNodeName() *string {
	return m.node_name
}

// GetTier gets the tier property value. The tier property
// returns a *string when successful
func (m *CsxRead) GetTier() *string {
	return m.tier
}

// Serialize serializes information the current object
func (m *CsxRead) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt64Value("at_ms", m.GetAtMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("duration_ns", m.GetDurationNs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("node_name", m.GetNodeName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("tier", m.GetTier())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CsxRead) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAtMs sets the at_ms property value. The at_ms property
func (m *CsxRead) SetAtMs(value *int64) {
	m.at_ms = value
}

// SetDurationNs sets the duration_ns property value. The duration_ns property
func (m *CsxRead) SetDurationNs(value *int64) {
	m.duration_ns = value
}

// SetNodeName sets the node_name property value. The node_name property
func (m *CsxRead) SetNodeName(value *string) {
	m.node_name = value
}

// SetTier sets the tier property value. The tier property
func (m *CsxRead) SetTier(value *string) {
	m.tier = value
}

type CsxReadable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAtMs() *int64
	GetDurationNs() *int64
	GetNodeName() *string
	GetTier() *string
	SetAtMs(value *int64)
	SetDurationNs(value *int64)
	SetNodeName(value *string)
	SetTier(value *string)
}
