// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type DispatchSummary struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The by_profile property
	by_profile []DispatchProfileSummaryable
	// The by_worker property
	by_worker []DispatchWorkerSummaryable
	// What became of the requests that were parked: the restore-versus-coldpayoff, measured on the requests that waited for it.
	hold_outcomes DispatchHoldOutcomesable
	// The holds property
	holds []DispatchHoldSummaryable
	// One point per minute over the window, by first-seen time.
	series []DispatchSeriesPointable
	// The totals property
	totals DispatchTotalsable
	// The window property
	window DispatchWindowable
}

// NewDispatchSummary instantiates a new DispatchSummary and sets the default values.
func NewDispatchSummary() *DispatchSummary {
	m := &DispatchSummary{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateDispatchSummaryFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDispatchSummaryFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewDispatchSummary(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DispatchSummary) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetByProfile gets the by_profile property value. The by_profile property
// returns a []DispatchProfileSummaryable when successful
func (m *DispatchSummary) GetByProfile() []DispatchProfileSummaryable {
	return m.by_profile
}

// GetByWorker gets the by_worker property value. The by_worker property
// returns a []DispatchWorkerSummaryable when successful
func (m *DispatchSummary) GetByWorker() []DispatchWorkerSummaryable {
	return m.by_worker
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *DispatchSummary) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["by_profile"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateDispatchProfileSummaryFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]DispatchProfileSummaryable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(DispatchProfileSummaryable)
				}
			}
			m.SetByProfile(res)
		}
		return nil
	}
	res["by_worker"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateDispatchWorkerSummaryFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]DispatchWorkerSummaryable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(DispatchWorkerSummaryable)
				}
			}
			m.SetByWorker(res)
		}
		return nil
	}
	res["hold_outcomes"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDispatchHoldOutcomesFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetHoldOutcomes(val.(DispatchHoldOutcomesable))
		}
		return nil
	}
	res["holds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateDispatchHoldSummaryFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]DispatchHoldSummaryable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(DispatchHoldSummaryable)
				}
			}
			m.SetHolds(res)
		}
		return nil
	}
	res["series"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateDispatchSeriesPointFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]DispatchSeriesPointable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(DispatchSeriesPointable)
				}
			}
			m.SetSeries(res)
		}
		return nil
	}
	res["totals"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDispatchTotalsFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTotals(val.(DispatchTotalsable))
		}
		return nil
	}
	res["window"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateDispatchWindowFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetWindow(val.(DispatchWindowable))
		}
		return nil
	}
	return res
}

// GetHoldOutcomes gets the hold_outcomes property value. What became of the requests that were parked: the restore-versus-coldpayoff, measured on the requests that waited for it.
// returns a DispatchHoldOutcomesable when successful
func (m *DispatchSummary) GetHoldOutcomes() DispatchHoldOutcomesable {
	return m.hold_outcomes
}

// GetHolds gets the holds property value. The holds property
// returns a []DispatchHoldSummaryable when successful
func (m *DispatchSummary) GetHolds() []DispatchHoldSummaryable {
	return m.holds
}

// GetSeries gets the series property value. One point per minute over the window, by first-seen time.
// returns a []DispatchSeriesPointable when successful
func (m *DispatchSummary) GetSeries() []DispatchSeriesPointable {
	return m.series
}

// GetTotals gets the totals property value. The totals property
// returns a DispatchTotalsable when successful
func (m *DispatchSummary) GetTotals() DispatchTotalsable {
	return m.totals
}

// GetWindow gets the window property value. The window property
// returns a DispatchWindowable when successful
func (m *DispatchSummary) GetWindow() DispatchWindowable {
	return m.window
}

// Serialize serializes information the current object
func (m *DispatchSummary) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetByProfile() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetByProfile()))
		for i, v := range m.GetByProfile() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("by_profile", cast)
		if err != nil {
			return err
		}
	}
	if m.GetByWorker() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetByWorker()))
		for i, v := range m.GetByWorker() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("by_worker", cast)
		if err != nil {
			return err
		}
	}
	if m.GetHolds() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetHolds()))
		for i, v := range m.GetHolds() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("holds", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("hold_outcomes", m.GetHoldOutcomes())
		if err != nil {
			return err
		}
	}
	if m.GetSeries() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetSeries()))
		for i, v := range m.GetSeries() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("series", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("totals", m.GetTotals())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("window", m.GetWindow())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DispatchSummary) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetByProfile sets the by_profile property value. The by_profile property
func (m *DispatchSummary) SetByProfile(value []DispatchProfileSummaryable) {
	m.by_profile = value
}

// SetByWorker sets the by_worker property value. The by_worker property
func (m *DispatchSummary) SetByWorker(value []DispatchWorkerSummaryable) {
	m.by_worker = value
}

// SetHoldOutcomes sets the hold_outcomes property value. What became of the requests that were parked: the restore-versus-coldpayoff, measured on the requests that waited for it.
func (m *DispatchSummary) SetHoldOutcomes(value DispatchHoldOutcomesable) {
	m.hold_outcomes = value
}

// SetHolds sets the holds property value. The holds property
func (m *DispatchSummary) SetHolds(value []DispatchHoldSummaryable) {
	m.holds = value
}

// SetSeries sets the series property value. One point per minute over the window, by first-seen time.
func (m *DispatchSummary) SetSeries(value []DispatchSeriesPointable) {
	m.series = value
}

// SetTotals sets the totals property value. The totals property
func (m *DispatchSummary) SetTotals(value DispatchTotalsable) {
	m.totals = value
}

// SetWindow sets the window property value. The window property
func (m *DispatchSummary) SetWindow(value DispatchWindowable) {
	m.window = value
}

type DispatchSummaryable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetByProfile() []DispatchProfileSummaryable
	GetByWorker() []DispatchWorkerSummaryable
	GetHoldOutcomes() DispatchHoldOutcomesable
	GetHolds() []DispatchHoldSummaryable
	GetSeries() []DispatchSeriesPointable
	GetTotals() DispatchTotalsable
	GetWindow() DispatchWindowable
	SetByProfile(value []DispatchProfileSummaryable)
	SetByWorker(value []DispatchWorkerSummaryable)
	SetHoldOutcomes(value DispatchHoldOutcomesable)
	SetHolds(value []DispatchHoldSummaryable)
	SetSeries(value []DispatchSeriesPointable)
	SetTotals(value DispatchTotalsable)
	SetWindow(value DispatchWindowable)
}
