// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
)

// DispatchView one dispatch, joined with the completion facts once Switchyard hasreported them. `completed` false means the request is still in flight orits telemetry never arrived; every usage field is then null.
type DispatchView struct {
	// The activation_path property
	activation_path *string
	// The active_streams property
	active_streams *int64
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The attempts property
	attempts *int32
	// The cached_tokens property
	cached_tokens *int64
	// The completed property
	completed *bool
	// The completion_tokens property
	completion_tokens *int64
	// The created_at property
	created_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// The decision_source property
	decision_source *string
	// The dispatch_id property
	dispatch_id *int64
	// The end_to_end_latency_ms property
	end_to_end_latency_ms *int64
	// The estimated_prompt_tokens property
	estimated_prompt_tokens *int64
	// The expected_ready_ms property
	expected_ready_ms *int64
	// The expected_reuse_tokens property
	expected_reuse_tokens *int64
	// The fallback_used property
	fallback_used *bool
	// The path a held request was forecast on: restore or cold. Distinctfrom the usage row's `activation_path`, which is what actually served.
	forecast_path *string
	// The hold_budget_ms property
	hold_budget_ms *int64
	// The hold_reason property
	hold_reason *string
	// The logical_model property
	logical_model *string
	// The outcome property
	outcome *string
	// The preference_reason property
	preference_reason *string
	// The preferred_profile_id property
	preferred_profile_id *string
	// The profile_id property
	profile_id *string
	// The prompt_tokens property
	prompt_tokens *int64
	// The queued_requests property
	queued_requests *int64
	// The ready_replicas property
	ready_replicas *int32
	// The request_id property
	request_id *string
	// The retry_after_ms property
	retry_after_ms *int64
	// The status_code property
	status_code *int32
	// The ttft_ms property
	ttft_ms *int64
	// The updated_at property
	updated_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// `pod` or `profile`: how far the worker columns can be trusted.
	worker_basis *string
	// The worker_checkpoint_path property
	worker_checkpoint_path *string
	// The worker_node_name property
	worker_node_name *string
	// The worker_pod_name property
	worker_pod_name *string
	// The worker_start_kind property
	worker_start_kind *string
}

// NewDispatchView instantiates a new DispatchView and sets the default values.
func NewDispatchView() *DispatchView {
	m := &DispatchView{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateDispatchViewFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDispatchViewFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewDispatchView(), nil
}

// GetActivationPath gets the activation_path property value. The activation_path property
// returns a *string when successful
func (m *DispatchView) GetActivationPath() *string {
	return m.activation_path
}

// GetActiveStreams gets the active_streams property value. The active_streams property
// returns a *int64 when successful
func (m *DispatchView) GetActiveStreams() *int64 {
	return m.active_streams
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DispatchView) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAttempts gets the attempts property value. The attempts property
// returns a *int32 when successful
func (m *DispatchView) GetAttempts() *int32 {
	return m.attempts
}

// GetCachedTokens gets the cached_tokens property value. The cached_tokens property
// returns a *int64 when successful
func (m *DispatchView) GetCachedTokens() *int64 {
	return m.cached_tokens
}

// GetCompleted gets the completed property value. The completed property
// returns a *bool when successful
func (m *DispatchView) GetCompleted() *bool {
	return m.completed
}

// GetCompletionTokens gets the completion_tokens property value. The completion_tokens property
// returns a *int64 when successful
func (m *DispatchView) GetCompletionTokens() *int64 {
	return m.completion_tokens
}

// GetCreatedAt gets the created_at property value. The created_at property
// returns a *Time when successful
func (m *DispatchView) GetCreatedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.created_at
}

// GetDecisionSource gets the decision_source property value. The decision_source property
// returns a *string when successful
func (m *DispatchView) GetDecisionSource() *string {
	return m.decision_source
}

// GetDispatchId gets the dispatch_id property value. The dispatch_id property
// returns a *int64 when successful
func (m *DispatchView) GetDispatchId() *int64 {
	return m.dispatch_id
}

// GetEndToEndLatencyMs gets the end_to_end_latency_ms property value. The end_to_end_latency_ms property
// returns a *int64 when successful
func (m *DispatchView) GetEndToEndLatencyMs() *int64 {
	return m.end_to_end_latency_ms
}

// GetEstimatedPromptTokens gets the estimated_prompt_tokens property value. The estimated_prompt_tokens property
// returns a *int64 when successful
func (m *DispatchView) GetEstimatedPromptTokens() *int64 {
	return m.estimated_prompt_tokens
}

// GetExpectedReadyMs gets the expected_ready_ms property value. The expected_ready_ms property
// returns a *int64 when successful
func (m *DispatchView) GetExpectedReadyMs() *int64 {
	return m.expected_ready_ms
}

// GetExpectedReuseTokens gets the expected_reuse_tokens property value. The expected_reuse_tokens property
// returns a *int64 when successful
func (m *DispatchView) GetExpectedReuseTokens() *int64 {
	return m.expected_reuse_tokens
}

// GetFallbackUsed gets the fallback_used property value. The fallback_used property
// returns a *bool when successful
func (m *DispatchView) GetFallbackUsed() *bool {
	return m.fallback_used
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *DispatchView) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["activation_path"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetActivationPath(val)
		}
		return nil
	}
	res["active_streams"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetActiveStreams(val)
		}
		return nil
	}
	res["attempts"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAttempts(val)
		}
		return nil
	}
	res["cached_tokens"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCachedTokens(val)
		}
		return nil
	}
	res["completed"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCompleted(val)
		}
		return nil
	}
	res["completion_tokens"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCompletionTokens(val)
		}
		return nil
	}
	res["created_at"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCreatedAt(val)
		}
		return nil
	}
	res["decision_source"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDecisionSource(val)
		}
		return nil
	}
	res["dispatch_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDispatchId(val)
		}
		return nil
	}
	res["end_to_end_latency_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetEndToEndLatencyMs(val)
		}
		return nil
	}
	res["estimated_prompt_tokens"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetEstimatedPromptTokens(val)
		}
		return nil
	}
	res["expected_ready_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetExpectedReadyMs(val)
		}
		return nil
	}
	res["expected_reuse_tokens"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetExpectedReuseTokens(val)
		}
		return nil
	}
	res["fallback_used"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetFallbackUsed(val)
		}
		return nil
	}
	res["forecast_path"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetForecastPath(val)
		}
		return nil
	}
	res["hold_budget_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetHoldBudgetMs(val)
		}
		return nil
	}
	res["hold_reason"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetHoldReason(val)
		}
		return nil
	}
	res["logical_model"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLogicalModel(val)
		}
		return nil
	}
	res["outcome"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetOutcome(val)
		}
		return nil
	}
	res["preference_reason"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPreferenceReason(val)
		}
		return nil
	}
	res["preferred_profile_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPreferredProfileId(val)
		}
		return nil
	}
	res["profile_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProfileId(val)
		}
		return nil
	}
	res["prompt_tokens"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPromptTokens(val)
		}
		return nil
	}
	res["queued_requests"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetQueuedRequests(val)
		}
		return nil
	}
	res["ready_replicas"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetReadyReplicas(val)
		}
		return nil
	}
	res["request_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRequestId(val)
		}
		return nil
	}
	res["retry_after_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRetryAfterMs(val)
		}
		return nil
	}
	res["status_code"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetStatusCode(val)
		}
		return nil
	}
	res["ttft_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTtftMs(val)
		}
		return nil
	}
	res["updated_at"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUpdatedAt(val)
		}
		return nil
	}
	res["worker_basis"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetWorkerBasis(val)
		}
		return nil
	}
	res["worker_checkpoint_path"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetWorkerCheckpointPath(val)
		}
		return nil
	}
	res["worker_node_name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetWorkerNodeName(val)
		}
		return nil
	}
	res["worker_pod_name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetWorkerPodName(val)
		}
		return nil
	}
	res["worker_start_kind"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetWorkerStartKind(val)
		}
		return nil
	}
	return res
}

// GetForecastPath gets the forecast_path property value. The path a held request was forecast on: restore or cold. Distinctfrom the usage row's `activation_path`, which is what actually served.
// returns a *string when successful
func (m *DispatchView) GetForecastPath() *string {
	return m.forecast_path
}

// GetHoldBudgetMs gets the hold_budget_ms property value. The hold_budget_ms property
// returns a *int64 when successful
func (m *DispatchView) GetHoldBudgetMs() *int64 {
	return m.hold_budget_ms
}

// GetHoldReason gets the hold_reason property value. The hold_reason property
// returns a *string when successful
func (m *DispatchView) GetHoldReason() *string {
	return m.hold_reason
}

// GetLogicalModel gets the logical_model property value. The logical_model property
// returns a *string when successful
func (m *DispatchView) GetLogicalModel() *string {
	return m.logical_model
}

// GetOutcome gets the outcome property value. The outcome property
// returns a *string when successful
func (m *DispatchView) GetOutcome() *string {
	return m.outcome
}

// GetPreferenceReason gets the preference_reason property value. The preference_reason property
// returns a *string when successful
func (m *DispatchView) GetPreferenceReason() *string {
	return m.preference_reason
}

// GetPreferredProfileId gets the preferred_profile_id property value. The preferred_profile_id property
// returns a *string when successful
func (m *DispatchView) GetPreferredProfileId() *string {
	return m.preferred_profile_id
}

// GetProfileId gets the profile_id property value. The profile_id property
// returns a *string when successful
func (m *DispatchView) GetProfileId() *string {
	return m.profile_id
}

// GetPromptTokens gets the prompt_tokens property value. The prompt_tokens property
// returns a *int64 when successful
func (m *DispatchView) GetPromptTokens() *int64 {
	return m.prompt_tokens
}

// GetQueuedRequests gets the queued_requests property value. The queued_requests property
// returns a *int64 when successful
func (m *DispatchView) GetQueuedRequests() *int64 {
	return m.queued_requests
}

// GetReadyReplicas gets the ready_replicas property value. The ready_replicas property
// returns a *int32 when successful
func (m *DispatchView) GetReadyReplicas() *int32 {
	return m.ready_replicas
}

// GetRequestId gets the request_id property value. The request_id property
// returns a *string when successful
func (m *DispatchView) GetRequestId() *string {
	return m.request_id
}

// GetRetryAfterMs gets the retry_after_ms property value. The retry_after_ms property
// returns a *int64 when successful
func (m *DispatchView) GetRetryAfterMs() *int64 {
	return m.retry_after_ms
}

// GetStatusCode gets the status_code property value. The status_code property
// returns a *int32 when successful
func (m *DispatchView) GetStatusCode() *int32 {
	return m.status_code
}

// GetTtftMs gets the ttft_ms property value. The ttft_ms property
// returns a *int64 when successful
func (m *DispatchView) GetTtftMs() *int64 {
	return m.ttft_ms
}

// GetUpdatedAt gets the updated_at property value. The updated_at property
// returns a *Time when successful
func (m *DispatchView) GetUpdatedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.updated_at
}

// GetWorkerBasis gets the worker_basis property value. `pod` or `profile`: how far the worker columns can be trusted.
// returns a *string when successful
func (m *DispatchView) GetWorkerBasis() *string {
	return m.worker_basis
}

// GetWorkerCheckpointPath gets the worker_checkpoint_path property value. The worker_checkpoint_path property
// returns a *string when successful
func (m *DispatchView) GetWorkerCheckpointPath() *string {
	return m.worker_checkpoint_path
}

// GetWorkerNodeName gets the worker_node_name property value. The worker_node_name property
// returns a *string when successful
func (m *DispatchView) GetWorkerNodeName() *string {
	return m.worker_node_name
}

// GetWorkerPodName gets the worker_pod_name property value. The worker_pod_name property
// returns a *string when successful
func (m *DispatchView) GetWorkerPodName() *string {
	return m.worker_pod_name
}

// GetWorkerStartKind gets the worker_start_kind property value. The worker_start_kind property
// returns a *string when successful
func (m *DispatchView) GetWorkerStartKind() *string {
	return m.worker_start_kind
}

// Serialize serializes information the current object
func (m *DispatchView) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("activation_path", m.GetActivationPath())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("active_streams", m.GetActiveStreams())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("attempts", m.GetAttempts())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("cached_tokens", m.GetCachedTokens())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("completed", m.GetCompleted())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("completion_tokens", m.GetCompletionTokens())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteTimeValue("created_at", m.GetCreatedAt())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("decision_source", m.GetDecisionSource())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("dispatch_id", m.GetDispatchId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("end_to_end_latency_ms", m.GetEndToEndLatencyMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("estimated_prompt_tokens", m.GetEstimatedPromptTokens())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("expected_ready_ms", m.GetExpectedReadyMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("expected_reuse_tokens", m.GetExpectedReuseTokens())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("fallback_used", m.GetFallbackUsed())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("forecast_path", m.GetForecastPath())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("hold_budget_ms", m.GetHoldBudgetMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("hold_reason", m.GetHoldReason())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("logical_model", m.GetLogicalModel())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("outcome", m.GetOutcome())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("preference_reason", m.GetPreferenceReason())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("preferred_profile_id", m.GetPreferredProfileId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("profile_id", m.GetProfileId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("prompt_tokens", m.GetPromptTokens())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("queued_requests", m.GetQueuedRequests())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("ready_replicas", m.GetReadyReplicas())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("request_id", m.GetRequestId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("retry_after_ms", m.GetRetryAfterMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("status_code", m.GetStatusCode())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("ttft_ms", m.GetTtftMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteTimeValue("updated_at", m.GetUpdatedAt())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("worker_basis", m.GetWorkerBasis())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("worker_checkpoint_path", m.GetWorkerCheckpointPath())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("worker_node_name", m.GetWorkerNodeName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("worker_pod_name", m.GetWorkerPodName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("worker_start_kind", m.GetWorkerStartKind())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetActivationPath sets the activation_path property value. The activation_path property
func (m *DispatchView) SetActivationPath(value *string) {
	m.activation_path = value
}

// SetActiveStreams sets the active_streams property value. The active_streams property
func (m *DispatchView) SetActiveStreams(value *int64) {
	m.active_streams = value
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DispatchView) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAttempts sets the attempts property value. The attempts property
func (m *DispatchView) SetAttempts(value *int32) {
	m.attempts = value
}

// SetCachedTokens sets the cached_tokens property value. The cached_tokens property
func (m *DispatchView) SetCachedTokens(value *int64) {
	m.cached_tokens = value
}

// SetCompleted sets the completed property value. The completed property
func (m *DispatchView) SetCompleted(value *bool) {
	m.completed = value
}

// SetCompletionTokens sets the completion_tokens property value. The completion_tokens property
func (m *DispatchView) SetCompletionTokens(value *int64) {
	m.completion_tokens = value
}

// SetCreatedAt sets the created_at property value. The created_at property
func (m *DispatchView) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.created_at = value
}

// SetDecisionSource sets the decision_source property value. The decision_source property
func (m *DispatchView) SetDecisionSource(value *string) {
	m.decision_source = value
}

// SetDispatchId sets the dispatch_id property value. The dispatch_id property
func (m *DispatchView) SetDispatchId(value *int64) {
	m.dispatch_id = value
}

// SetEndToEndLatencyMs sets the end_to_end_latency_ms property value. The end_to_end_latency_ms property
func (m *DispatchView) SetEndToEndLatencyMs(value *int64) {
	m.end_to_end_latency_ms = value
}

// SetEstimatedPromptTokens sets the estimated_prompt_tokens property value. The estimated_prompt_tokens property
func (m *DispatchView) SetEstimatedPromptTokens(value *int64) {
	m.estimated_prompt_tokens = value
}

// SetExpectedReadyMs sets the expected_ready_ms property value. The expected_ready_ms property
func (m *DispatchView) SetExpectedReadyMs(value *int64) {
	m.expected_ready_ms = value
}

// SetExpectedReuseTokens sets the expected_reuse_tokens property value. The expected_reuse_tokens property
func (m *DispatchView) SetExpectedReuseTokens(value *int64) {
	m.expected_reuse_tokens = value
}

// SetFallbackUsed sets the fallback_used property value. The fallback_used property
func (m *DispatchView) SetFallbackUsed(value *bool) {
	m.fallback_used = value
}

// SetForecastPath sets the forecast_path property value. The path a held request was forecast on: restore or cold. Distinctfrom the usage row's `activation_path`, which is what actually served.
func (m *DispatchView) SetForecastPath(value *string) {
	m.forecast_path = value
}

// SetHoldBudgetMs sets the hold_budget_ms property value. The hold_budget_ms property
func (m *DispatchView) SetHoldBudgetMs(value *int64) {
	m.hold_budget_ms = value
}

// SetHoldReason sets the hold_reason property value. The hold_reason property
func (m *DispatchView) SetHoldReason(value *string) {
	m.hold_reason = value
}

// SetLogicalModel sets the logical_model property value. The logical_model property
func (m *DispatchView) SetLogicalModel(value *string) {
	m.logical_model = value
}

// SetOutcome sets the outcome property value. The outcome property
func (m *DispatchView) SetOutcome(value *string) {
	m.outcome = value
}

// SetPreferenceReason sets the preference_reason property value. The preference_reason property
func (m *DispatchView) SetPreferenceReason(value *string) {
	m.preference_reason = value
}

// SetPreferredProfileId sets the preferred_profile_id property value. The preferred_profile_id property
func (m *DispatchView) SetPreferredProfileId(value *string) {
	m.preferred_profile_id = value
}

// SetProfileId sets the profile_id property value. The profile_id property
func (m *DispatchView) SetProfileId(value *string) {
	m.profile_id = value
}

// SetPromptTokens sets the prompt_tokens property value. The prompt_tokens property
func (m *DispatchView) SetPromptTokens(value *int64) {
	m.prompt_tokens = value
}

// SetQueuedRequests sets the queued_requests property value. The queued_requests property
func (m *DispatchView) SetQueuedRequests(value *int64) {
	m.queued_requests = value
}

// SetReadyReplicas sets the ready_replicas property value. The ready_replicas property
func (m *DispatchView) SetReadyReplicas(value *int32) {
	m.ready_replicas = value
}

// SetRequestId sets the request_id property value. The request_id property
func (m *DispatchView) SetRequestId(value *string) {
	m.request_id = value
}

// SetRetryAfterMs sets the retry_after_ms property value. The retry_after_ms property
func (m *DispatchView) SetRetryAfterMs(value *int64) {
	m.retry_after_ms = value
}

// SetStatusCode sets the status_code property value. The status_code property
func (m *DispatchView) SetStatusCode(value *int32) {
	m.status_code = value
}

// SetTtftMs sets the ttft_ms property value. The ttft_ms property
func (m *DispatchView) SetTtftMs(value *int64) {
	m.ttft_ms = value
}

// SetUpdatedAt sets the updated_at property value. The updated_at property
func (m *DispatchView) SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.updated_at = value
}

// SetWorkerBasis sets the worker_basis property value. `pod` or `profile`: how far the worker columns can be trusted.
func (m *DispatchView) SetWorkerBasis(value *string) {
	m.worker_basis = value
}

// SetWorkerCheckpointPath sets the worker_checkpoint_path property value. The worker_checkpoint_path property
func (m *DispatchView) SetWorkerCheckpointPath(value *string) {
	m.worker_checkpoint_path = value
}

// SetWorkerNodeName sets the worker_node_name property value. The worker_node_name property
func (m *DispatchView) SetWorkerNodeName(value *string) {
	m.worker_node_name = value
}

// SetWorkerPodName sets the worker_pod_name property value. The worker_pod_name property
func (m *DispatchView) SetWorkerPodName(value *string) {
	m.worker_pod_name = value
}

// SetWorkerStartKind sets the worker_start_kind property value. The worker_start_kind property
func (m *DispatchView) SetWorkerStartKind(value *string) {
	m.worker_start_kind = value
}

type DispatchViewable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetActivationPath() *string
	GetActiveStreams() *int64
	GetAttempts() *int32
	GetCachedTokens() *int64
	GetCompleted() *bool
	GetCompletionTokens() *int64
	GetCreatedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetDecisionSource() *string
	GetDispatchId() *int64
	GetEndToEndLatencyMs() *int64
	GetEstimatedPromptTokens() *int64
	GetExpectedReadyMs() *int64
	GetExpectedReuseTokens() *int64
	GetFallbackUsed() *bool
	GetForecastPath() *string
	GetHoldBudgetMs() *int64
	GetHoldReason() *string
	GetLogicalModel() *string
	GetOutcome() *string
	GetPreferenceReason() *string
	GetPreferredProfileId() *string
	GetProfileId() *string
	GetPromptTokens() *int64
	GetQueuedRequests() *int64
	GetReadyReplicas() *int32
	GetRequestId() *string
	GetRetryAfterMs() *int64
	GetStatusCode() *int32
	GetTtftMs() *int64
	GetUpdatedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetWorkerBasis() *string
	GetWorkerCheckpointPath() *string
	GetWorkerNodeName() *string
	GetWorkerPodName() *string
	GetWorkerStartKind() *string
	SetActivationPath(value *string)
	SetActiveStreams(value *int64)
	SetAttempts(value *int32)
	SetCachedTokens(value *int64)
	SetCompleted(value *bool)
	SetCompletionTokens(value *int64)
	SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetDecisionSource(value *string)
	SetDispatchId(value *int64)
	SetEndToEndLatencyMs(value *int64)
	SetEstimatedPromptTokens(value *int64)
	SetExpectedReadyMs(value *int64)
	SetExpectedReuseTokens(value *int64)
	SetFallbackUsed(value *bool)
	SetForecastPath(value *string)
	SetHoldBudgetMs(value *int64)
	SetHoldReason(value *string)
	SetLogicalModel(value *string)
	SetOutcome(value *string)
	SetPreferenceReason(value *string)
	SetPreferredProfileId(value *string)
	SetProfileId(value *string)
	SetPromptTokens(value *int64)
	SetQueuedRequests(value *int64)
	SetReadyReplicas(value *int32)
	SetRequestId(value *string)
	SetRetryAfterMs(value *int64)
	SetStatusCode(value *int32)
	SetTtftMs(value *int64)
	SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetWorkerBasis(value *string)
	SetWorkerCheckpointPath(value *string)
	SetWorkerNodeName(value *string)
	SetWorkerPodName(value *string)
	SetWorkerStartKind(value *string)
}
