// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// DispatchProfileSummary per profile: how requests were dispatched to it and what served them.
type DispatchProfileSummary struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The assigned property
	assigned *int64
	// The avg_ttft_ms property
	avg_ttft_ms *float64
	// Engine-reported cached prompt tokens, summed. Null when nothingreported it, never zero.
	cached_tokens *int64
	// The classifier property
	classifier *int64
	// The completed property
	completed *int64
	// The completion_tokens property
	completion_tokens *int64
	// The expected_reuse_tokens property
	expected_reuse_tokens *int64
	// The failed property
	failed *int64
	// The fallback property
	fallback *int64
	// Assigned because Switchyard's prefix affinity asked for this profile.
	kv_affinity *int64
	// The logical_model property
	logical_model *string
	// The p50_ttft_ms property
	p50_ttft_ms *float64
	// The parked property
	parked *int64
	// The profile_id property
	profile_id *string
	// The prompt_tokens property
	prompt_tokens *int64
	// The rejected property
	rejected *int64
	// The served_by_cold_worker property
	served_by_cold_worker *int64
	// Assigned to a worker that had restored from a checkpoint.
	served_by_restored_worker *int64
	// Assigned with no single worker to attribute (several replicas, or nopod visible). Counted separately so the two above never look completewhen they are not.
	served_unattributed *int64
}

// NewDispatchProfileSummary instantiates a new DispatchProfileSummary and sets the default values.
func NewDispatchProfileSummary() *DispatchProfileSummary {
	m := &DispatchProfileSummary{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateDispatchProfileSummaryFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDispatchProfileSummaryFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewDispatchProfileSummary(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DispatchProfileSummary) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAssigned gets the assigned property value. The assigned property
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetAssigned() *int64 {
	return m.assigned
}

// GetAvgTtftMs gets the avg_ttft_ms property value. The avg_ttft_ms property
// returns a *float64 when successful
func (m *DispatchProfileSummary) GetAvgTtftMs() *float64 {
	return m.avg_ttft_ms
}

// GetCachedTokens gets the cached_tokens property value. Engine-reported cached prompt tokens, summed. Null when nothingreported it, never zero.
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetCachedTokens() *int64 {
	return m.cached_tokens
}

// GetClassifier gets the classifier property value. The classifier property
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetClassifier() *int64 {
	return m.classifier
}

// GetCompleted gets the completed property value. The completed property
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetCompleted() *int64 {
	return m.completed
}

// GetCompletionTokens gets the completion_tokens property value. The completion_tokens property
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetCompletionTokens() *int64 {
	return m.completion_tokens
}

// GetExpectedReuseTokens gets the expected_reuse_tokens property value. The expected_reuse_tokens property
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetExpectedReuseTokens() *int64 {
	return m.expected_reuse_tokens
}

// GetFailed gets the failed property value. The failed property
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetFailed() *int64 {
	return m.failed
}

// GetFallback gets the fallback property value. The fallback property
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetFallback() *int64 {
	return m.fallback
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *DispatchProfileSummary) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["assigned"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAssigned(val)
		}
		return nil
	}
	res["avg_ttft_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAvgTtftMs(val)
		}
		return nil
	}
	res["cached_tokens"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCachedTokens(val)
		}
		return nil
	}
	res["classifier"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetClassifier(val)
		}
		return nil
	}
	res["completed"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCompleted(val)
		}
		return nil
	}
	res["completion_tokens"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCompletionTokens(val)
		}
		return nil
	}
	res["expected_reuse_tokens"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetExpectedReuseTokens(val)
		}
		return nil
	}
	res["failed"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetFailed(val)
		}
		return nil
	}
	res["fallback"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetFallback(val)
		}
		return nil
	}
	res["kv_affinity"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetKvAffinity(val)
		}
		return nil
	}
	res["logical_model"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLogicalModel(val)
		}
		return nil
	}
	res["p50_ttft_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetP50TtftMs(val)
		}
		return nil
	}
	res["parked"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetParked(val)
		}
		return nil
	}
	res["profile_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProfileId(val)
		}
		return nil
	}
	res["prompt_tokens"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPromptTokens(val)
		}
		return nil
	}
	res["rejected"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRejected(val)
		}
		return nil
	}
	res["served_by_cold_worker"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetServedByColdWorker(val)
		}
		return nil
	}
	res["served_by_restored_worker"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetServedByRestoredWorker(val)
		}
		return nil
	}
	res["served_unattributed"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetServedUnattributed(val)
		}
		return nil
	}
	return res
}

// GetKvAffinity gets the kv_affinity property value. Assigned because Switchyard's prefix affinity asked for this profile.
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetKvAffinity() *int64 {
	return m.kv_affinity
}

// GetLogicalModel gets the logical_model property value. The logical_model property
// returns a *string when successful
func (m *DispatchProfileSummary) GetLogicalModel() *string {
	return m.logical_model
}

// GetP50TtftMs gets the p50_ttft_ms property value. The p50_ttft_ms property
// returns a *float64 when successful
func (m *DispatchProfileSummary) GetP50TtftMs() *float64 {
	return m.p50_ttft_ms
}

// GetParked gets the parked property value. The parked property
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetParked() *int64 {
	return m.parked
}

// GetProfileId gets the profile_id property value. The profile_id property
// returns a *string when successful
func (m *DispatchProfileSummary) GetProfileId() *string {
	return m.profile_id
}

// GetPromptTokens gets the prompt_tokens property value. The prompt_tokens property
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetPromptTokens() *int64 {
	return m.prompt_tokens
}

// GetRejected gets the rejected property value. The rejected property
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetRejected() *int64 {
	return m.rejected
}

// GetServedByColdWorker gets the served_by_cold_worker property value. The served_by_cold_worker property
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetServedByColdWorker() *int64 {
	return m.served_by_cold_worker
}

// GetServedByRestoredWorker gets the served_by_restored_worker property value. Assigned to a worker that had restored from a checkpoint.
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetServedByRestoredWorker() *int64 {
	return m.served_by_restored_worker
}

// GetServedUnattributed gets the served_unattributed property value. Assigned with no single worker to attribute (several replicas, or nopod visible). Counted separately so the two above never look completewhen they are not.
// returns a *int64 when successful
func (m *DispatchProfileSummary) GetServedUnattributed() *int64 {
	return m.served_unattributed
}

// Serialize serializes information the current object
func (m *DispatchProfileSummary) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt64Value("assigned", m.GetAssigned())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("avg_ttft_ms", m.GetAvgTtftMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("cached_tokens", m.GetCachedTokens())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("classifier", m.GetClassifier())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("completed", m.GetCompleted())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("completion_tokens", m.GetCompletionTokens())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("expected_reuse_tokens", m.GetExpectedReuseTokens())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("failed", m.GetFailed())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("fallback", m.GetFallback())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("kv_affinity", m.GetKvAffinity())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("logical_model", m.GetLogicalModel())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("p50_ttft_ms", m.GetP50TtftMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("parked", m.GetParked())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("profile_id", m.GetProfileId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("prompt_tokens", m.GetPromptTokens())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("rejected", m.GetRejected())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("served_by_cold_worker", m.GetServedByColdWorker())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("served_by_restored_worker", m.GetServedByRestoredWorker())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("served_unattributed", m.GetServedUnattributed())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DispatchProfileSummary) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAssigned sets the assigned property value. The assigned property
func (m *DispatchProfileSummary) SetAssigned(value *int64) {
	m.assigned = value
}

// SetAvgTtftMs sets the avg_ttft_ms property value. The avg_ttft_ms property
func (m *DispatchProfileSummary) SetAvgTtftMs(value *float64) {
	m.avg_ttft_ms = value
}

// SetCachedTokens sets the cached_tokens property value. Engine-reported cached prompt tokens, summed. Null when nothingreported it, never zero.
func (m *DispatchProfileSummary) SetCachedTokens(value *int64) {
	m.cached_tokens = value
}

// SetClassifier sets the classifier property value. The classifier property
func (m *DispatchProfileSummary) SetClassifier(value *int64) {
	m.classifier = value
}

// SetCompleted sets the completed property value. The completed property
func (m *DispatchProfileSummary) SetCompleted(value *int64) {
	m.completed = value
}

// SetCompletionTokens sets the completion_tokens property value. The completion_tokens property
func (m *DispatchProfileSummary) SetCompletionTokens(value *int64) {
	m.completion_tokens = value
}

// SetExpectedReuseTokens sets the expected_reuse_tokens property value. The expected_reuse_tokens property
func (m *DispatchProfileSummary) SetExpectedReuseTokens(value *int64) {
	m.expected_reuse_tokens = value
}

// SetFailed sets the failed property value. The failed property
func (m *DispatchProfileSummary) SetFailed(value *int64) {
	m.failed = value
}

// SetFallback sets the fallback property value. The fallback property
func (m *DispatchProfileSummary) SetFallback(value *int64) {
	m.fallback = value
}

// SetKvAffinity sets the kv_affinity property value. Assigned because Switchyard's prefix affinity asked for this profile.
func (m *DispatchProfileSummary) SetKvAffinity(value *int64) {
	m.kv_affinity = value
}

// SetLogicalModel sets the logical_model property value. The logical_model property
func (m *DispatchProfileSummary) SetLogicalModel(value *string) {
	m.logical_model = value
}

// SetP50TtftMs sets the p50_ttft_ms property value. The p50_ttft_ms property
func (m *DispatchProfileSummary) SetP50TtftMs(value *float64) {
	m.p50_ttft_ms = value
}

// SetParked sets the parked property value. The parked property
func (m *DispatchProfileSummary) SetParked(value *int64) {
	m.parked = value
}

// SetProfileId sets the profile_id property value. The profile_id property
func (m *DispatchProfileSummary) SetProfileId(value *string) {
	m.profile_id = value
}

// SetPromptTokens sets the prompt_tokens property value. The prompt_tokens property
func (m *DispatchProfileSummary) SetPromptTokens(value *int64) {
	m.prompt_tokens = value
}

// SetRejected sets the rejected property value. The rejected property
func (m *DispatchProfileSummary) SetRejected(value *int64) {
	m.rejected = value
}

// SetServedByColdWorker sets the served_by_cold_worker property value. The served_by_cold_worker property
func (m *DispatchProfileSummary) SetServedByColdWorker(value *int64) {
	m.served_by_cold_worker = value
}

// SetServedByRestoredWorker sets the served_by_restored_worker property value. Assigned to a worker that had restored from a checkpoint.
func (m *DispatchProfileSummary) SetServedByRestoredWorker(value *int64) {
	m.served_by_restored_worker = value
}

// SetServedUnattributed sets the served_unattributed property value. Assigned with no single worker to attribute (several replicas, or nopod visible). Counted separately so the two above never look completewhen they are not.
func (m *DispatchProfileSummary) SetServedUnattributed(value *int64) {
	m.served_unattributed = value
}

type DispatchProfileSummaryable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAssigned() *int64
	GetAvgTtftMs() *float64
	GetCachedTokens() *int64
	GetClassifier() *int64
	GetCompleted() *int64
	GetCompletionTokens() *int64
	GetExpectedReuseTokens() *int64
	GetFailed() *int64
	GetFallback() *int64
	GetKvAffinity() *int64
	GetLogicalModel() *string
	GetP50TtftMs() *float64
	GetParked() *int64
	GetProfileId() *string
	GetPromptTokens() *int64
	GetRejected() *int64
	GetServedByColdWorker() *int64
	GetServedByRestoredWorker() *int64
	GetServedUnattributed() *int64
	SetAssigned(value *int64)
	SetAvgTtftMs(value *float64)
	SetCachedTokens(value *int64)
	SetClassifier(value *int64)
	SetCompleted(value *int64)
	SetCompletionTokens(value *int64)
	SetExpectedReuseTokens(value *int64)
	SetFailed(value *int64)
	SetFallback(value *int64)
	SetKvAffinity(value *int64)
	SetLogicalModel(value *string)
	SetP50TtftMs(value *float64)
	SetParked(value *int64)
	SetProfileId(value *string)
	SetPromptTokens(value *int64)
	SetRejected(value *int64)
	SetServedByColdWorker(value *int64)
	SetServedByRestoredWorker(value *int64)
	SetServedUnattributed(value *int64)
}
