// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// GpuInfo gPU inventory of one node.
type GpuInfo struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// nvidia.com/gpu the scheduler can hand out (excludes MIG slices)
	allocatable *int64
	// Compute capability, e.g. "9.0"
	compute_capability *string
	// Physical GPUs on the node
	count *int64
	// Highest CUDA version the driver supports, e.g. "12.4"
	cuda_version *string
	// NVIDIA driver version, e.g. "550.54.15"
	driver_version *string
	// Architecture family, e.g. "hopper"
	family *string
	// Memory per GPU in MiB
	memory_mib *int64
	// Allocatable MIG slices by profile, e.g. {"1g.10gb": 7}; empty when MIG is off
	mig_devices GpuInfo_mig_devicesable
	// MIG strategy ("none", "single" or "mixed"), or "disabled" when mig-manager has MIG off
	mig_strategy *string
	// GPU model, e.g. "NVIDIA-H100-80GB-HBM3"
	product *string
}

// NewGpuInfo instantiates a new GpuInfo and sets the default values.
func NewGpuInfo() *GpuInfo {
	m := &GpuInfo{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateGpuInfoFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGpuInfoFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewGpuInfo(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *GpuInfo) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAllocatable gets the allocatable property value. nvidia.com/gpu the scheduler can hand out (excludes MIG slices)
// returns a *int64 when successful
func (m *GpuInfo) GetAllocatable() *int64 {
	return m.allocatable
}

// GetComputeCapability gets the compute_capability property value. Compute capability, e.g. "9.0"
// returns a *string when successful
func (m *GpuInfo) GetComputeCapability() *string {
	return m.compute_capability
}

// GetCount gets the count property value. Physical GPUs on the node
// returns a *int64 when successful
func (m *GpuInfo) GetCount() *int64 {
	return m.count
}

// GetCudaVersion gets the cuda_version property value. Highest CUDA version the driver supports, e.g. "12.4"
// returns a *string when successful
func (m *GpuInfo) GetCudaVersion() *string {
	return m.cuda_version
}

// GetDriverVersion gets the driver_version property value. NVIDIA driver version, e.g. "550.54.15"
// returns a *string when successful
func (m *GpuInfo) GetDriverVersion() *string {
	return m.driver_version
}

// GetFamily gets the family property value. Architecture family, e.g. "hopper"
// returns a *string when successful
func (m *GpuInfo) GetFamily() *string {
	return m.family
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *GpuInfo) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["allocatable"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAllocatable(val)
		}
		return nil
	}
	res["compute_capability"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetComputeCapability(val)
		}
		return nil
	}
	res["count"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCount(val)
		}
		return nil
	}
	res["cuda_version"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCudaVersion(val)
		}
		return nil
	}
	res["driver_version"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDriverVersion(val)
		}
		return nil
	}
	res["family"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetFamily(val)
		}
		return nil
	}
	res["memory_mib"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMemoryMib(val)
		}
		return nil
	}
	res["mig_devices"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateGpuInfo_mig_devicesFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMigDevices(val.(GpuInfo_mig_devicesable))
		}
		return nil
	}
	res["mig_strategy"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMigStrategy(val)
		}
		return nil
	}
	res["product"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProduct(val)
		}
		return nil
	}
	return res
}

// GetMemoryMib gets the memory_mib property value. Memory per GPU in MiB
// returns a *int64 when successful
func (m *GpuInfo) GetMemoryMib() *int64 {
	return m.memory_mib
}

// GetMigDevices gets the mig_devices property value. Allocatable MIG slices by profile, e.g. {"1g.10gb": 7}; empty when MIG is off
// returns a GpuInfo_mig_devicesable when successful
func (m *GpuInfo) GetMigDevices() GpuInfo_mig_devicesable {
	return m.mig_devices
}

// GetMigStrategy gets the mig_strategy property value. MIG strategy ("none", "single" or "mixed"), or "disabled" when mig-manager has MIG off
// returns a *string when successful
func (m *GpuInfo) GetMigStrategy() *string {
	return m.mig_strategy
}

// GetProduct gets the product property value. GPU model, e.g. "NVIDIA-H100-80GB-HBM3"
// returns a *string when successful
func (m *GpuInfo) GetProduct() *string {
	return m.product
}

// Serialize serializes information the current object
func (m *GpuInfo) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt64Value("allocatable", m.GetAllocatable())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("compute_capability", m.GetComputeCapability())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("count", m.GetCount())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("cuda_version", m.GetCudaVersion())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("driver_version", m.GetDriverVersion())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("family", m.GetFamily())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("memory_mib", m.GetMemoryMib())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("mig_devices", m.GetMigDevices())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("mig_strategy", m.GetMigStrategy())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("product", m.GetProduct())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *GpuInfo) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAllocatable sets the allocatable property value. nvidia.com/gpu the scheduler can hand out (excludes MIG slices)
func (m *GpuInfo) SetAllocatable(value *int64) {
	m.allocatable = value
}

// SetComputeCapability sets the compute_capability property value. Compute capability, e.g. "9.0"
func (m *GpuInfo) SetComputeCapability(value *string) {
	m.compute_capability = value
}

// SetCount sets the count property value. Physical GPUs on the node
func (m *GpuInfo) SetCount(value *int64) {
	m.count = value
}

// SetCudaVersion sets the cuda_version property value. Highest CUDA version the driver supports, e.g. "12.4"
func (m *GpuInfo) SetCudaVersion(value *string) {
	m.cuda_version = value
}

// SetDriverVersion sets the driver_version property value. NVIDIA driver version, e.g. "550.54.15"
func (m *GpuInfo) SetDriverVersion(value *string) {
	m.driver_version = value
}

// SetFamily sets the family property value. Architecture family, e.g. "hopper"
func (m *GpuInfo) SetFamily(value *string) {
	m.family = value
}

// SetMemoryMib sets the memory_mib property value. Memory per GPU in MiB
func (m *GpuInfo) SetMemoryMib(value *int64) {
	m.memory_mib = value
}

// SetMigDevices sets the mig_devices property value. Allocatable MIG slices by profile, e.g. {"1g.10gb": 7}; empty when MIG is off
func (m *GpuInfo) SetMigDevices(value GpuInfo_mig_devicesable) {
	m.mig_devices = value
}

// SetMigStrategy sets the mig_strategy property value. MIG strategy ("none", "single" or "mixed"), or "disabled" when mig-manager has MIG off
func (m *GpuInfo) SetMigStrategy(value *string) {
	m.mig_strategy = value
}

// SetProduct sets the product property value. GPU model, e.g. "NVIDIA-H100-80GB-HBM3"
func (m *GpuInfo) SetProduct(value *string) {
	m.product = value
}

type GpuInfoable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAllocatable() *int64
	GetComputeCapability() *string
	GetCount() *int64
	GetCudaVersion() *string
	GetDriverVersion() *string
	GetFamily() *string
	GetMemoryMib() *int64
	GetMigDevices() GpuInfo_mig_devicesable
	GetMigStrategy() *string
	GetProduct() *string
	SetAllocatable(value *int64)
	SetComputeCapability(value *string)
	SetCount(value *int64)
	SetCudaVersion(value *string)
	SetDriverVersion(value *string)
	SetFamily(value *string)
	SetMemoryMib(value *int64)
	SetMigDevices(value GpuInfo_mig_devicesable)
	SetMigStrategy(value *string)
	SetProduct(value *string)
}
