// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type HistoryPage struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The next property
	next HistoryCursorable
	// The records property
	records []HistoryRecordable
}

// NewHistoryPage instantiates a new HistoryPage and sets the default values.
func NewHistoryPage() *HistoryPage {
	m := &HistoryPage{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateHistoryPageFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateHistoryPageFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewHistoryPage(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *HistoryPage) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *HistoryPage) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["next"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateHistoryCursorFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNext(val.(HistoryCursorable))
		}
		return nil
	}
	res["records"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateHistoryRecordFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]HistoryRecordable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(HistoryRecordable)
				}
			}
			m.SetRecords(res)
		}
		return nil
	}
	return res
}

// GetNext gets the next property value. The next property
// returns a HistoryCursorable when successful
func (m *HistoryPage) GetNext() HistoryCursorable {
	return m.next
}

// GetRecords gets the records property value. The records property
// returns a []HistoryRecordable when successful
func (m *HistoryPage) GetRecords() []HistoryRecordable {
	return m.records
}

// Serialize serializes information the current object
func (m *HistoryPage) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteObjectValue("next", m.GetNext())
		if err != nil {
			return err
		}
	}
	if m.GetRecords() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetRecords()))
		for i, v := range m.GetRecords() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("records", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *HistoryPage) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetNext sets the next property value. The next property
func (m *HistoryPage) SetNext(value HistoryCursorable) {
	m.next = value
}

// SetRecords sets the records property value. The records property
func (m *HistoryPage) SetRecords(value []HistoryRecordable) {
	m.records = value
}

type HistoryPageable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetNext() HistoryCursorable
	GetRecords() []HistoryRecordable
	SetNext(value HistoryCursorable)
	SetRecords(value []HistoryRecordable)
}
