// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

type LifetimeState int

const (
	HEARTBEAT_LIFETIMESTATE LifetimeState = iota
	FINISHED_LIFETIMESTATE
	CANCELLED_LIFETIMESTATE
)

func (i LifetimeState) String() string {
	return []string{"heartbeat", "finished", "cancelled"}[i]
}

func ParseLifetimeState(v string) (any, error) {
	result := HEARTBEAT_LIFETIMESTATE
	switch v {
	case "heartbeat":
		result = HEARTBEAT_LIFETIMESTATE
	case "finished":
		result = FINISHED_LIFETIMESTATE
	case "cancelled":
		result = CANCELLED_LIFETIMESTATE
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeLifetimeState(values []LifetimeState) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i LifetimeState) isMultiValue() bool {
	return false
}
