// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// LmcacheSeries one `lmcache_*` metric for one worker pod over the window. Counters arecumulative as the engine reports them; a reader takes deltas for rates.
type LmcacheSeries struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The metric_name property
	metric_name *string
	// The pod_name property
	pod_name *string
	// `[unix_ms, value]` pairs, ascending.
	points []i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
}

// NewLmcacheSeries instantiates a new LmcacheSeries and sets the default values.
func NewLmcacheSeries() *LmcacheSeries {
	m := &LmcacheSeries{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateLmcacheSeriesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateLmcacheSeriesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewLmcacheSeries(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *LmcacheSeries) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *LmcacheSeries) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["metric_name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMetricName(val)
		}
		return nil
	}
	res["pod_name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPodName(val)
		}
		return nil
	}
	res["points"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("untypednodeable")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *(v.(*i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
				}
			}
			m.SetPoints(res)
		}
		return nil
	}
	return res
}

// GetMetricName gets the metric_name property value. The metric_name property
// returns a *string when successful
func (m *LmcacheSeries) GetMetricName() *string {
	return m.metric_name
}

// GetPodName gets the pod_name property value. The pod_name property
// returns a *string when successful
func (m *LmcacheSeries) GetPodName() *string {
	return m.pod_name
}

// GetPoints gets the points property value. `[unix_ms, value]` pairs, ascending.
// returns a []UntypedNodeable when successful
func (m *LmcacheSeries) GetPoints() []i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable {
	return m.points
}

// Serialize serializes information the current object
func (m *LmcacheSeries) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("metric_name", m.GetMetricName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("pod_name", m.GetPodName())
		if err != nil {
			return err
		}
	}
	if m.GetPoints() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetPoints()))
		for i, v := range m.GetPoints() {
			if v != nil {
				temp := v
				cast[i] = i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable(&temp)
			}
		}
		err := writer.WriteCollectionOfObjectValues("points", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *LmcacheSeries) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetMetricName sets the metric_name property value. The metric_name property
func (m *LmcacheSeries) SetMetricName(value *string) {
	m.metric_name = value
}

// SetPodName sets the pod_name property value. The pod_name property
func (m *LmcacheSeries) SetPodName(value *string) {
	m.pod_name = value
}

// SetPoints sets the points property value. `[unix_ms, value]` pairs, ascending.
func (m *LmcacheSeries) SetPoints(value []i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
	m.points = value
}

type LmcacheSeriesable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetMetricName() *string
	GetPodName() *string
	GetPoints() []i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
	SetMetricName(value *string)
	SetPodName(value *string)
	SetPoints(value []i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
}
