// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type LmcacheSeriesResponse struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The bucket_seconds property
	bucket_seconds *int64
	// Newest sample in the window, or null when the profile never reported LMCache.
	latest_ms *int64
	// The minutes property
	minutes *int64
	// The profile_id property
	profile_id *string
	// The series property
	series []LmcacheSeriesable
}

// NewLmcacheSeriesResponse instantiates a new LmcacheSeriesResponse and sets the default values.
func NewLmcacheSeriesResponse() *LmcacheSeriesResponse {
	m := &LmcacheSeriesResponse{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateLmcacheSeriesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateLmcacheSeriesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewLmcacheSeriesResponse(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *LmcacheSeriesResponse) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetBucketSeconds gets the bucket_seconds property value. The bucket_seconds property
// returns a *int64 when successful
func (m *LmcacheSeriesResponse) GetBucketSeconds() *int64 {
	return m.bucket_seconds
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *LmcacheSeriesResponse) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["bucket_seconds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetBucketSeconds(val)
		}
		return nil
	}
	res["latest_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLatestMs(val)
		}
		return nil
	}
	res["minutes"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMinutes(val)
		}
		return nil
	}
	res["profile_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProfileId(val)
		}
		return nil
	}
	res["series"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateLmcacheSeriesFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]LmcacheSeriesable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(LmcacheSeriesable)
				}
			}
			m.SetSeries(res)
		}
		return nil
	}
	return res
}

// GetLatestMs gets the latest_ms property value. Newest sample in the window, or null when the profile never reported LMCache.
// returns a *int64 when successful
func (m *LmcacheSeriesResponse) GetLatestMs() *int64 {
	return m.latest_ms
}

// GetMinutes gets the minutes property value. The minutes property
// returns a *int64 when successful
func (m *LmcacheSeriesResponse) GetMinutes() *int64 {
	return m.minutes
}

// GetProfileId gets the profile_id property value. The profile_id property
// returns a *string when successful
func (m *LmcacheSeriesResponse) GetProfileId() *string {
	return m.profile_id
}

// GetSeries gets the series property value. The series property
// returns a []LmcacheSeriesable when successful
func (m *LmcacheSeriesResponse) GetSeries() []LmcacheSeriesable {
	return m.series
}

// Serialize serializes information the current object
func (m *LmcacheSeriesResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt64Value("bucket_seconds", m.GetBucketSeconds())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("latest_ms", m.GetLatestMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("minutes", m.GetMinutes())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("profile_id", m.GetProfileId())
		if err != nil {
			return err
		}
	}
	if m.GetSeries() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetSeries()))
		for i, v := range m.GetSeries() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("series", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *LmcacheSeriesResponse) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetBucketSeconds sets the bucket_seconds property value. The bucket_seconds property
func (m *LmcacheSeriesResponse) SetBucketSeconds(value *int64) {
	m.bucket_seconds = value
}

// SetLatestMs sets the latest_ms property value. Newest sample in the window, or null when the profile never reported LMCache.
func (m *LmcacheSeriesResponse) SetLatestMs(value *int64) {
	m.latest_ms = value
}

// SetMinutes sets the minutes property value. The minutes property
func (m *LmcacheSeriesResponse) SetMinutes(value *int64) {
	m.minutes = value
}

// SetProfileId sets the profile_id property value. The profile_id property
func (m *LmcacheSeriesResponse) SetProfileId(value *string) {
	m.profile_id = value
}

// SetSeries sets the series property value. The series property
func (m *LmcacheSeriesResponse) SetSeries(value []LmcacheSeriesable) {
	m.series = value
}

type LmcacheSeriesResponseable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetBucketSeconds() *int64
	GetLatestMs() *int64
	GetMinutes() *int64
	GetProfileId() *string
	GetSeries() []LmcacheSeriesable
	SetBucketSeconds(value *int64)
	SetLatestMs(value *int64)
	SetMinutes(value *int64)
	SetProfileId(value *string)
	SetSeries(value []LmcacheSeriesable)
}
