// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// NetworkInfo networking of one node: NICs, RDMA and the devices plugins expose for them.
type NetworkInfo struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Whether the NVIDIA Network Operator manages this node's NIC drivers
	network_operator *bool
	// High-performance NIC vendors seen on the PCI bus, e.g. ["NVIDIA Mellanox"] (Node Feature Discovery)
	nic_vendors []string
	// Whether the RDMA kernel modules are loaded (Node Feature Discovery)
	rdma_available *bool
	// Whether an RDMA-capable NIC is present (Node Feature Discovery)
	rdma_capable *bool
	// RDMA, InfiniBand, SR-IOV and EFA devices the node advertises, by resource name, e.g. {"rdma/ib": 8}
	rdma_resources NetworkInfo_rdma_resourcesable
	// Whether a NIC supports SR-IOV (Node Feature Discovery)
	sriov_capable *bool
	// Whether SR-IOV virtual functions are configured (Node Feature Discovery)
	sriov_configured *bool
}

// NewNetworkInfo instantiates a new NetworkInfo and sets the default values.
func NewNetworkInfo() *NetworkInfo {
	m := &NetworkInfo{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateNetworkInfoFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateNetworkInfoFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewNetworkInfo(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *NetworkInfo) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *NetworkInfo) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["network_operator"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNetworkOperator(val)
		}
		return nil
	}
	res["nic_vendors"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *(v.(*string))
				}
			}
			m.SetNicVendors(res)
		}
		return nil
	}
	res["rdma_available"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRdmaAvailable(val)
		}
		return nil
	}
	res["rdma_capable"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRdmaCapable(val)
		}
		return nil
	}
	res["rdma_resources"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateNetworkInfo_rdma_resourcesFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRdmaResources(val.(NetworkInfo_rdma_resourcesable))
		}
		return nil
	}
	res["sriov_capable"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSriovCapable(val)
		}
		return nil
	}
	res["sriov_configured"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSriovConfigured(val)
		}
		return nil
	}
	return res
}

// GetNetworkOperator gets the network_operator property value. Whether the NVIDIA Network Operator manages this node's NIC drivers
// returns a *bool when successful
func (m *NetworkInfo) GetNetworkOperator() *bool {
	return m.network_operator
}

// GetNicVendors gets the nic_vendors property value. High-performance NIC vendors seen on the PCI bus, e.g. ["NVIDIA Mellanox"] (Node Feature Discovery)
// returns a []string when successful
func (m *NetworkInfo) GetNicVendors() []string {
	return m.nic_vendors
}

// GetRdmaAvailable gets the rdma_available property value. Whether the RDMA kernel modules are loaded (Node Feature Discovery)
// returns a *bool when successful
func (m *NetworkInfo) GetRdmaAvailable() *bool {
	return m.rdma_available
}

// GetRdmaCapable gets the rdma_capable property value. Whether an RDMA-capable NIC is present (Node Feature Discovery)
// returns a *bool when successful
func (m *NetworkInfo) GetRdmaCapable() *bool {
	return m.rdma_capable
}

// GetRdmaResources gets the rdma_resources property value. RDMA, InfiniBand, SR-IOV and EFA devices the node advertises, by resource name, e.g. {"rdma/ib": 8}
// returns a NetworkInfo_rdma_resourcesable when successful
func (m *NetworkInfo) GetRdmaResources() NetworkInfo_rdma_resourcesable {
	return m.rdma_resources
}

// GetSriovCapable gets the sriov_capable property value. Whether a NIC supports SR-IOV (Node Feature Discovery)
// returns a *bool when successful
func (m *NetworkInfo) GetSriovCapable() *bool {
	return m.sriov_capable
}

// GetSriovConfigured gets the sriov_configured property value. Whether SR-IOV virtual functions are configured (Node Feature Discovery)
// returns a *bool when successful
func (m *NetworkInfo) GetSriovConfigured() *bool {
	return m.sriov_configured
}

// Serialize serializes information the current object
func (m *NetworkInfo) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteBoolValue("network_operator", m.GetNetworkOperator())
		if err != nil {
			return err
		}
	}
	if m.GetNicVendors() != nil {
		err := writer.WriteCollectionOfStringValues("nic_vendors", m.GetNicVendors())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("rdma_available", m.GetRdmaAvailable())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("rdma_capable", m.GetRdmaCapable())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("rdma_resources", m.GetRdmaResources())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("sriov_capable", m.GetSriovCapable())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("sriov_configured", m.GetSriovConfigured())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *NetworkInfo) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetNetworkOperator sets the network_operator property value. Whether the NVIDIA Network Operator manages this node's NIC drivers
func (m *NetworkInfo) SetNetworkOperator(value *bool) {
	m.network_operator = value
}

// SetNicVendors sets the nic_vendors property value. High-performance NIC vendors seen on the PCI bus, e.g. ["NVIDIA Mellanox"] (Node Feature Discovery)
func (m *NetworkInfo) SetNicVendors(value []string) {
	m.nic_vendors = value
}

// SetRdmaAvailable sets the rdma_available property value. Whether the RDMA kernel modules are loaded (Node Feature Discovery)
func (m *NetworkInfo) SetRdmaAvailable(value *bool) {
	m.rdma_available = value
}

// SetRdmaCapable sets the rdma_capable property value. Whether an RDMA-capable NIC is present (Node Feature Discovery)
func (m *NetworkInfo) SetRdmaCapable(value *bool) {
	m.rdma_capable = value
}

// SetRdmaResources sets the rdma_resources property value. RDMA, InfiniBand, SR-IOV and EFA devices the node advertises, by resource name, e.g. {"rdma/ib": 8}
func (m *NetworkInfo) SetRdmaResources(value NetworkInfo_rdma_resourcesable) {
	m.rdma_resources = value
}

// SetSriovCapable sets the sriov_capable property value. Whether a NIC supports SR-IOV (Node Feature Discovery)
func (m *NetworkInfo) SetSriovCapable(value *bool) {
	m.sriov_capable = value
}

// SetSriovConfigured sets the sriov_configured property value. Whether SR-IOV virtual functions are configured (Node Feature Discovery)
func (m *NetworkInfo) SetSriovConfigured(value *bool) {
	m.sriov_configured = value
}

type NetworkInfoable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetNetworkOperator() *bool
	GetNicVendors() []string
	GetRdmaAvailable() *bool
	GetRdmaCapable() *bool
	GetRdmaResources() NetworkInfo_rdma_resourcesable
	GetSriovCapable() *bool
	GetSriovConfigured() *bool
	SetNetworkOperator(value *bool)
	SetNicVendors(value []string)
	SetRdmaAvailable(value *bool)
	SetRdmaCapable(value *bool)
	SetRdmaResources(value NetworkInfo_rdma_resourcesable)
	SetSriovCapable(value *bool)
	SetSriovConfigured(value *bool)
}
