// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type NodeResponse struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// "spot" or "on-demand" - detected from node labels
	capacity_type *string
	// The cluster_name property
	cluster_name *string
	// The compute_type property
	compute_type *string
	// The cpu property
	cpu CpuInfoable
	// The gpu property
	gpu GpuInfoable
	// The id property
	id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
	// The instance_type property
	instance_type *string
	// Node labels, without NFD's per-flag CPUID labels
	labels NodeResponse_labelsable
	// The name property
	name *string
	// The network property
	network NetworkInfoable
	// The region property
	region *string
	// The status property
	status *string
	// The storage property
	storage StorageInfoable
	// The system property
	system SystemInfoable
}

// NewNodeResponse instantiates a new NodeResponse and sets the default values.
func NewNodeResponse() *NodeResponse {
	m := &NodeResponse{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateNodeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateNodeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewNodeResponse(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *NodeResponse) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetCapacityType gets the capacity_type property value. "spot" or "on-demand" - detected from node labels
// returns a *string when successful
func (m *NodeResponse) GetCapacityType() *string {
	return m.capacity_type
}

// GetClusterName gets the cluster_name property value. The cluster_name property
// returns a *string when successful
func (m *NodeResponse) GetClusterName() *string {
	return m.cluster_name
}

// GetComputeType gets the compute_type property value. The compute_type property
// returns a *string when successful
func (m *NodeResponse) GetComputeType() *string {
	return m.compute_type
}

// GetCpu gets the cpu property value. The cpu property
// returns a CpuInfoable when successful
func (m *NodeResponse) GetCpu() CpuInfoable {
	return m.cpu
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *NodeResponse) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["capacity_type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCapacityType(val)
		}
		return nil
	}
	res["cluster_name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetClusterName(val)
		}
		return nil
	}
	res["compute_type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetComputeType(val)
		}
		return nil
	}
	res["cpu"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateCpuInfoFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCpu(val.(CpuInfoable))
		}
		return nil
	}
	res["gpu"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateGpuInfoFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetGpu(val.(GpuInfoable))
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetUUIDValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["instance_type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetInstanceType(val)
		}
		return nil
	}
	res["labels"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateNodeResponse_labelsFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLabels(val.(NodeResponse_labelsable))
		}
		return nil
	}
	res["name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetName(val)
		}
		return nil
	}
	res["network"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateNetworkInfoFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNetwork(val.(NetworkInfoable))
		}
		return nil
	}
	res["region"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRegion(val)
		}
		return nil
	}
	res["status"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetStatus(val)
		}
		return nil
	}
	res["storage"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateStorageInfoFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetStorage(val.(StorageInfoable))
		}
		return nil
	}
	res["system"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateSystemInfoFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSystem(val.(SystemInfoable))
		}
		return nil
	}
	return res
}

// GetGpu gets the gpu property value. The gpu property
// returns a GpuInfoable when successful
func (m *NodeResponse) GetGpu() GpuInfoable {
	return m.gpu
}

// GetId gets the id property value. The id property
// returns a *UUID when successful
func (m *NodeResponse) GetId() *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID {
	return m.id
}

// GetInstanceType gets the instance_type property value. The instance_type property
// returns a *string when successful
func (m *NodeResponse) GetInstanceType() *string {
	return m.instance_type
}

// GetLabels gets the labels property value. Node labels, without NFD's per-flag CPUID labels
// returns a NodeResponse_labelsable when successful
func (m *NodeResponse) GetLabels() NodeResponse_labelsable {
	return m.labels
}

// GetName gets the name property value. The name property
// returns a *string when successful
func (m *NodeResponse) GetName() *string {
	return m.name
}

// GetNetwork gets the network property value. The network property
// returns a NetworkInfoable when successful
func (m *NodeResponse) GetNetwork() NetworkInfoable {
	return m.network
}

// GetRegion gets the region property value. The region property
// returns a *string when successful
func (m *NodeResponse) GetRegion() *string {
	return m.region
}

// GetStatus gets the status property value. The status property
// returns a *string when successful
func (m *NodeResponse) GetStatus() *string {
	return m.status
}

// GetStorage gets the storage property value. The storage property
// returns a StorageInfoable when successful
func (m *NodeResponse) GetStorage() StorageInfoable {
	return m.storage
}

// GetSystem gets the system property value. The system property
// returns a SystemInfoable when successful
func (m *NodeResponse) GetSystem() SystemInfoable {
	return m.system
}

// Serialize serializes information the current object
func (m *NodeResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("capacity_type", m.GetCapacityType())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("cluster_name", m.GetClusterName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("compute_type", m.GetComputeType())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("cpu", m.GetCpu())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("gpu", m.GetGpu())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteUUIDValue("id", m.GetId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("instance_type", m.GetInstanceType())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("labels", m.GetLabels())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("name", m.GetName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("network", m.GetNetwork())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("region", m.GetRegion())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("status", m.GetStatus())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("storage", m.GetStorage())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("system", m.GetSystem())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *NodeResponse) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetCapacityType sets the capacity_type property value. "spot" or "on-demand" - detected from node labels
func (m *NodeResponse) SetCapacityType(value *string) {
	m.capacity_type = value
}

// SetClusterName sets the cluster_name property value. The cluster_name property
func (m *NodeResponse) SetClusterName(value *string) {
	m.cluster_name = value
}

// SetComputeType sets the compute_type property value. The compute_type property
func (m *NodeResponse) SetComputeType(value *string) {
	m.compute_type = value
}

// SetCpu sets the cpu property value. The cpu property
func (m *NodeResponse) SetCpu(value CpuInfoable) {
	m.cpu = value
}

// SetGpu sets the gpu property value. The gpu property
func (m *NodeResponse) SetGpu(value GpuInfoable) {
	m.gpu = value
}

// SetId sets the id property value. The id property
func (m *NodeResponse) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
	m.id = value
}

// SetInstanceType sets the instance_type property value. The instance_type property
func (m *NodeResponse) SetInstanceType(value *string) {
	m.instance_type = value
}

// SetLabels sets the labels property value. Node labels, without NFD's per-flag CPUID labels
func (m *NodeResponse) SetLabels(value NodeResponse_labelsable) {
	m.labels = value
}

// SetName sets the name property value. The name property
func (m *NodeResponse) SetName(value *string) {
	m.name = value
}

// SetNetwork sets the network property value. The network property
func (m *NodeResponse) SetNetwork(value NetworkInfoable) {
	m.network = value
}

// SetRegion sets the region property value. The region property
func (m *NodeResponse) SetRegion(value *string) {
	m.region = value
}

// SetStatus sets the status property value. The status property
func (m *NodeResponse) SetStatus(value *string) {
	m.status = value
}

// SetStorage sets the storage property value. The storage property
func (m *NodeResponse) SetStorage(value StorageInfoable) {
	m.storage = value
}

// SetSystem sets the system property value. The system property
func (m *NodeResponse) SetSystem(value SystemInfoable) {
	m.system = value
}

type NodeResponseable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetCapacityType() *string
	GetClusterName() *string
	GetComputeType() *string
	GetCpu() CpuInfoable
	GetGpu() GpuInfoable
	GetId() *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
	GetInstanceType() *string
	GetLabels() NodeResponse_labelsable
	GetName() *string
	GetNetwork() NetworkInfoable
	GetRegion() *string
	GetStatus() *string
	GetStorage() StorageInfoable
	GetSystem() SystemInfoable
	SetCapacityType(value *string)
	SetClusterName(value *string)
	SetComputeType(value *string)
	SetCpu(value CpuInfoable)
	SetGpu(value GpuInfoable)
	SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
	SetInstanceType(value *string)
	SetLabels(value NodeResponse_labelsable)
	SetName(value *string)
	SetNetwork(value NetworkInfoable)
	SetRegion(value *string)
	SetStatus(value *string)
	SetStorage(value StorageInfoable)
	SetSystem(value SystemInfoable)
}
