// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
)

// OrgCheckpointSavings organization-level checkpoint savings summary
type OrgCheckpointSavings struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The avg_checkpoint_interval_seconds property
	avg_checkpoint_interval_seconds *float64
	// The pods_protected property
	pods_protected *int64
	// The refreshed_at property
	refreshed_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// The total_checkpoint_overhead_ns property
	total_checkpoint_overhead_ns *int64
	// The total_checkpoint_storage_bytes property
	total_checkpoint_storage_bytes *int64
	// The total_checkpoints property
	total_checkpoints *int64
	// Total estimated savings across all pods (spot vs on-demand)
	total_estimated_savings *float64
	// The total_heartbeat_checkpoints property
	total_heartbeat_checkpoints *int64
	// The total_manual_checkpoints property
	total_manual_checkpoints *int64
	// The total_time_protected_seconds property
	total_time_protected_seconds *float64
	// The worst_case_recovery_point_seconds property
	worst_case_recovery_point_seconds *float64
}

// NewOrgCheckpointSavings instantiates a new OrgCheckpointSavings and sets the default values.
func NewOrgCheckpointSavings() *OrgCheckpointSavings {
	m := &OrgCheckpointSavings{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateOrgCheckpointSavingsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOrgCheckpointSavingsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewOrgCheckpointSavings(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *OrgCheckpointSavings) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAvgCheckpointIntervalSeconds gets the avg_checkpoint_interval_seconds property value. The avg_checkpoint_interval_seconds property
// returns a *float64 when successful
func (m *OrgCheckpointSavings) GetAvgCheckpointIntervalSeconds() *float64 {
	return m.avg_checkpoint_interval_seconds
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *OrgCheckpointSavings) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["avg_checkpoint_interval_seconds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAvgCheckpointIntervalSeconds(val)
		}
		return nil
	}
	res["pods_protected"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPodsProtected(val)
		}
		return nil
	}
	res["refreshed_at"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRefreshedAt(val)
		}
		return nil
	}
	res["total_checkpoint_overhead_ns"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTotalCheckpointOverheadNs(val)
		}
		return nil
	}
	res["total_checkpoint_storage_bytes"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTotalCheckpointStorageBytes(val)
		}
		return nil
	}
	res["total_checkpoints"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTotalCheckpoints(val)
		}
		return nil
	}
	res["total_estimated_savings"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTotalEstimatedSavings(val)
		}
		return nil
	}
	res["total_heartbeat_checkpoints"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTotalHeartbeatCheckpoints(val)
		}
		return nil
	}
	res["total_manual_checkpoints"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTotalManualCheckpoints(val)
		}
		return nil
	}
	res["total_time_protected_seconds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTotalTimeProtectedSeconds(val)
		}
		return nil
	}
	res["worst_case_recovery_point_seconds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetWorstCaseRecoveryPointSeconds(val)
		}
		return nil
	}
	return res
}

// GetPodsProtected gets the pods_protected property value. The pods_protected property
// returns a *int64 when successful
func (m *OrgCheckpointSavings) GetPodsProtected() *int64 {
	return m.pods_protected
}

// GetRefreshedAt gets the refreshed_at property value. The refreshed_at property
// returns a *Time when successful
func (m *OrgCheckpointSavings) GetRefreshedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.refreshed_at
}

// GetTotalCheckpointOverheadNs gets the total_checkpoint_overhead_ns property value. The total_checkpoint_overhead_ns property
// returns a *int64 when successful
func (m *OrgCheckpointSavings) GetTotalCheckpointOverheadNs() *int64 {
	return m.total_checkpoint_overhead_ns
}

// GetTotalCheckpoints gets the total_checkpoints property value. The total_checkpoints property
// returns a *int64 when successful
func (m *OrgCheckpointSavings) GetTotalCheckpoints() *int64 {
	return m.total_checkpoints
}

// GetTotalCheckpointStorageBytes gets the total_checkpoint_storage_bytes property value. The total_checkpoint_storage_bytes property
// returns a *int64 when successful
func (m *OrgCheckpointSavings) GetTotalCheckpointStorageBytes() *int64 {
	return m.total_checkpoint_storage_bytes
}

// GetTotalEstimatedSavings gets the total_estimated_savings property value. Total estimated savings across all pods (spot vs on-demand)
// returns a *float64 when successful
func (m *OrgCheckpointSavings) GetTotalEstimatedSavings() *float64 {
	return m.total_estimated_savings
}

// GetTotalHeartbeatCheckpoints gets the total_heartbeat_checkpoints property value. The total_heartbeat_checkpoints property
// returns a *int64 when successful
func (m *OrgCheckpointSavings) GetTotalHeartbeatCheckpoints() *int64 {
	return m.total_heartbeat_checkpoints
}

// GetTotalManualCheckpoints gets the total_manual_checkpoints property value. The total_manual_checkpoints property
// returns a *int64 when successful
func (m *OrgCheckpointSavings) GetTotalManualCheckpoints() *int64 {
	return m.total_manual_checkpoints
}

// GetTotalTimeProtectedSeconds gets the total_time_protected_seconds property value. The total_time_protected_seconds property
// returns a *float64 when successful
func (m *OrgCheckpointSavings) GetTotalTimeProtectedSeconds() *float64 {
	return m.total_time_protected_seconds
}

// GetWorstCaseRecoveryPointSeconds gets the worst_case_recovery_point_seconds property value. The worst_case_recovery_point_seconds property
// returns a *float64 when successful
func (m *OrgCheckpointSavings) GetWorstCaseRecoveryPointSeconds() *float64 {
	return m.worst_case_recovery_point_seconds
}

// Serialize serializes information the current object
func (m *OrgCheckpointSavings) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteFloat64Value("avg_checkpoint_interval_seconds", m.GetAvgCheckpointIntervalSeconds())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("pods_protected", m.GetPodsProtected())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteTimeValue("refreshed_at", m.GetRefreshedAt())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("total_checkpoints", m.GetTotalCheckpoints())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("total_checkpoint_overhead_ns", m.GetTotalCheckpointOverheadNs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("total_checkpoint_storage_bytes", m.GetTotalCheckpointStorageBytes())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("total_estimated_savings", m.GetTotalEstimatedSavings())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("total_heartbeat_checkpoints", m.GetTotalHeartbeatCheckpoints())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("total_manual_checkpoints", m.GetTotalManualCheckpoints())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("total_time_protected_seconds", m.GetTotalTimeProtectedSeconds())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("worst_case_recovery_point_seconds", m.GetWorstCaseRecoveryPointSeconds())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *OrgCheckpointSavings) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAvgCheckpointIntervalSeconds sets the avg_checkpoint_interval_seconds property value. The avg_checkpoint_interval_seconds property
func (m *OrgCheckpointSavings) SetAvgCheckpointIntervalSeconds(value *float64) {
	m.avg_checkpoint_interval_seconds = value
}

// SetPodsProtected sets the pods_protected property value. The pods_protected property
func (m *OrgCheckpointSavings) SetPodsProtected(value *int64) {
	m.pods_protected = value
}

// SetRefreshedAt sets the refreshed_at property value. The refreshed_at property
func (m *OrgCheckpointSavings) SetRefreshedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.refreshed_at = value
}

// SetTotalCheckpointOverheadNs sets the total_checkpoint_overhead_ns property value. The total_checkpoint_overhead_ns property
func (m *OrgCheckpointSavings) SetTotalCheckpointOverheadNs(value *int64) {
	m.total_checkpoint_overhead_ns = value
}

// SetTotalCheckpoints sets the total_checkpoints property value. The total_checkpoints property
func (m *OrgCheckpointSavings) SetTotalCheckpoints(value *int64) {
	m.total_checkpoints = value
}

// SetTotalCheckpointStorageBytes sets the total_checkpoint_storage_bytes property value. The total_checkpoint_storage_bytes property
func (m *OrgCheckpointSavings) SetTotalCheckpointStorageBytes(value *int64) {
	m.total_checkpoint_storage_bytes = value
}

// SetTotalEstimatedSavings sets the total_estimated_savings property value. Total estimated savings across all pods (spot vs on-demand)
func (m *OrgCheckpointSavings) SetTotalEstimatedSavings(value *float64) {
	m.total_estimated_savings = value
}

// SetTotalHeartbeatCheckpoints sets the total_heartbeat_checkpoints property value. The total_heartbeat_checkpoints property
func (m *OrgCheckpointSavings) SetTotalHeartbeatCheckpoints(value *int64) {
	m.total_heartbeat_checkpoints = value
}

// SetTotalManualCheckpoints sets the total_manual_checkpoints property value. The total_manual_checkpoints property
func (m *OrgCheckpointSavings) SetTotalManualCheckpoints(value *int64) {
	m.total_manual_checkpoints = value
}

// SetTotalTimeProtectedSeconds sets the total_time_protected_seconds property value. The total_time_protected_seconds property
func (m *OrgCheckpointSavings) SetTotalTimeProtectedSeconds(value *float64) {
	m.total_time_protected_seconds = value
}

// SetWorstCaseRecoveryPointSeconds sets the worst_case_recovery_point_seconds property value. The worst_case_recovery_point_seconds property
func (m *OrgCheckpointSavings) SetWorstCaseRecoveryPointSeconds(value *float64) {
	m.worst_case_recovery_point_seconds = value
}

type OrgCheckpointSavingsable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAvgCheckpointIntervalSeconds() *float64
	GetPodsProtected() *int64
	GetRefreshedAt() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetTotalCheckpointOverheadNs() *int64
	GetTotalCheckpoints() *int64
	GetTotalCheckpointStorageBytes() *int64
	GetTotalEstimatedSavings() *float64
	GetTotalHeartbeatCheckpoints() *int64
	GetTotalManualCheckpoints() *int64
	GetTotalTimeProtectedSeconds() *float64
	GetWorstCaseRecoveryPointSeconds() *float64
	SetAvgCheckpointIntervalSeconds(value *float64)
	SetPodsProtected(value *int64)
	SetRefreshedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetTotalCheckpointOverheadNs(value *int64)
	SetTotalCheckpoints(value *int64)
	SetTotalCheckpointStorageBytes(value *int64)
	SetTotalEstimatedSavings(value *float64)
	SetTotalHeartbeatCheckpoints(value *int64)
	SetTotalManualCheckpoints(value *int64)
	SetTotalTimeProtectedSeconds(value *float64)
	SetWorstCaseRecoveryPointSeconds(value *float64)
}
