// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
)

// PrefixHintView one prefix a parked or served request carried, in Switchyard's fingerprintspace. Opaque to everything except set intersection.
type PrefixHintView struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The last_seen property
	last_seen *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// How many parked requests carried this prefix. Always 1 on theserved-prefix inventory, which counts residency, not demand.
	parked_count *int64
	// The prefix_hash property
	prefix_hash *string
	// The prefix_tokens property
	prefix_tokens *int64
}

// NewPrefixHintView instantiates a new PrefixHintView and sets the default values.
func NewPrefixHintView() *PrefixHintView {
	m := &PrefixHintView{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreatePrefixHintViewFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePrefixHintViewFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewPrefixHintView(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PrefixHintView) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *PrefixHintView) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["last_seen"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLastSeen(val)
		}
		return nil
	}
	res["parked_count"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetParkedCount(val)
		}
		return nil
	}
	res["prefix_hash"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPrefixHash(val)
		}
		return nil
	}
	res["prefix_tokens"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPrefixTokens(val)
		}
		return nil
	}
	return res
}

// GetLastSeen gets the last_seen property value. The last_seen property
// returns a *Time when successful
func (m *PrefixHintView) GetLastSeen() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.last_seen
}

// GetParkedCount gets the parked_count property value. How many parked requests carried this prefix. Always 1 on theserved-prefix inventory, which counts residency, not demand.
// returns a *int64 when successful
func (m *PrefixHintView) GetParkedCount() *int64 {
	return m.parked_count
}

// GetPrefixHash gets the prefix_hash property value. The prefix_hash property
// returns a *string when successful
func (m *PrefixHintView) GetPrefixHash() *string {
	return m.prefix_hash
}

// GetPrefixTokens gets the prefix_tokens property value. The prefix_tokens property
// returns a *int64 when successful
func (m *PrefixHintView) GetPrefixTokens() *int64 {
	return m.prefix_tokens
}

// Serialize serializes information the current object
func (m *PrefixHintView) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteTimeValue("last_seen", m.GetLastSeen())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("parked_count", m.GetParkedCount())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("prefix_hash", m.GetPrefixHash())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("prefix_tokens", m.GetPrefixTokens())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PrefixHintView) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetLastSeen sets the last_seen property value. The last_seen property
func (m *PrefixHintView) SetLastSeen(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.last_seen = value
}

// SetParkedCount sets the parked_count property value. How many parked requests carried this prefix. Always 1 on theserved-prefix inventory, which counts residency, not demand.
func (m *PrefixHintView) SetParkedCount(value *int64) {
	m.parked_count = value
}

// SetPrefixHash sets the prefix_hash property value. The prefix_hash property
func (m *PrefixHintView) SetPrefixHash(value *string) {
	m.prefix_hash = value
}

// SetPrefixTokens sets the prefix_tokens property value. The prefix_tokens property
func (m *PrefixHintView) SetPrefixTokens(value *int64) {
	m.prefix_tokens = value
}

type PrefixHintViewable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetLastSeen() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetParkedCount() *int64
	GetPrefixHash() *string
	GetPrefixTokens() *int64
	SetLastSeen(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetParkedCount(value *int64)
	SetPrefixHash(value *string)
	SetPrefixTokens(value *int64)
}
