// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PrefixFingerprint one cumulative prefix fingerprint of the request body, in Switchyard'shash space: `tokens` is the estimated token length of the prefix and`hash` its fold, hex-encoded. Opaque here — recorded and intersected,never recomputed.
type PrefixFingerprint struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The hash property
	hash *string
	// The tokens property
	tokens *int64
}

// NewPrefixFingerprint instantiates a new PrefixFingerprint and sets the default values.
func NewPrefixFingerprint() *PrefixFingerprint {
	m := &PrefixFingerprint{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreatePrefixFingerprintFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePrefixFingerprintFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewPrefixFingerprint(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PrefixFingerprint) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *PrefixFingerprint) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["hash"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetHash(val)
		}
		return nil
	}
	res["tokens"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTokens(val)
		}
		return nil
	}
	return res
}

// GetHash gets the hash property value. The hash property
// returns a *string when successful
func (m *PrefixFingerprint) GetHash() *string {
	return m.hash
}

// GetTokens gets the tokens property value. The tokens property
// returns a *int64 when successful
func (m *PrefixFingerprint) GetTokens() *int64 {
	return m.tokens
}

// Serialize serializes information the current object
func (m *PrefixFingerprint) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("hash", m.GetHash())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("tokens", m.GetTokens())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PrefixFingerprint) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetHash sets the hash property value. The hash property
func (m *PrefixFingerprint) SetHash(value *string) {
	m.hash = value
}

// SetTokens sets the tokens property value. The tokens property
func (m *PrefixFingerprint) SetTokens(value *int64) {
	m.tokens = value
}

type PrefixFingerprintable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetHash() *string
	GetTokens() *int64
	SetHash(value *string)
	SetTokens(value *int64)
}
