// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ProfileUtilization struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The gpus property
	gpus *int64
	// The logical_model property
	logical_model *string
	// The mean_slice_s property
	mean_slice_s *float64
	// The profile_id property
	profile_id *string
	// Seconds a published route existed for the profile inside the window.
	resident_s *float64
	// Route publications inside the window: activations that completed.
	slices *int64
	// Median seconds the node spent switching before this profile served: its swapcost. Compare against a cold start for the same model.
	swap_p50_s *float64
	// 90th percentile of the same, so a regression is visible rather than averaged out.
	swap_p90_s *float64
	// Swaps into this profile that were measured (the node was empty beforehand).
	swaps_measured *int64
}

// NewProfileUtilization instantiates a new ProfileUtilization and sets the default values.
func NewProfileUtilization() *ProfileUtilization {
	m := &ProfileUtilization{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateProfileUtilizationFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateProfileUtilizationFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewProfileUtilization(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ProfileUtilization) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *ProfileUtilization) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["gpus"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetGpus(val)
		}
		return nil
	}
	res["logical_model"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLogicalModel(val)
		}
		return nil
	}
	res["mean_slice_s"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMeanSliceS(val)
		}
		return nil
	}
	res["profile_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProfileId(val)
		}
		return nil
	}
	res["resident_s"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetResidentS(val)
		}
		return nil
	}
	res["slices"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSlices(val)
		}
		return nil
	}
	res["swap_p50_s"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSwapP50S(val)
		}
		return nil
	}
	res["swap_p90_s"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSwapP90S(val)
		}
		return nil
	}
	res["swaps_measured"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSwapsMeasured(val)
		}
		return nil
	}
	return res
}

// GetGpus gets the gpus property value. The gpus property
// returns a *int64 when successful
func (m *ProfileUtilization) GetGpus() *int64 {
	return m.gpus
}

// GetLogicalModel gets the logical_model property value. The logical_model property
// returns a *string when successful
func (m *ProfileUtilization) GetLogicalModel() *string {
	return m.logical_model
}

// GetMeanSliceS gets the mean_slice_s property value. The mean_slice_s property
// returns a *float64 when successful
func (m *ProfileUtilization) GetMeanSliceS() *float64 {
	return m.mean_slice_s
}

// GetProfileId gets the profile_id property value. The profile_id property
// returns a *string when successful
func (m *ProfileUtilization) GetProfileId() *string {
	return m.profile_id
}

// GetResidentS gets the resident_s property value. Seconds a published route existed for the profile inside the window.
// returns a *float64 when successful
func (m *ProfileUtilization) GetResidentS() *float64 {
	return m.resident_s
}

// GetSlices gets the slices property value. Route publications inside the window: activations that completed.
// returns a *int64 when successful
func (m *ProfileUtilization) GetSlices() *int64 {
	return m.slices
}

// GetSwapP50S gets the swap_p50_s property value. Median seconds the node spent switching before this profile served: its swapcost. Compare against a cold start for the same model.
// returns a *float64 when successful
func (m *ProfileUtilization) GetSwapP50S() *float64 {
	return m.swap_p50_s
}

// GetSwapP90S gets the swap_p90_s property value. 90th percentile of the same, so a regression is visible rather than averaged out.
// returns a *float64 when successful
func (m *ProfileUtilization) GetSwapP90S() *float64 {
	return m.swap_p90_s
}

// GetSwapsMeasured gets the swaps_measured property value. Swaps into this profile that were measured (the node was empty beforehand).
// returns a *int64 when successful
func (m *ProfileUtilization) GetSwapsMeasured() *int64 {
	return m.swaps_measured
}

// Serialize serializes information the current object
func (m *ProfileUtilization) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt64Value("gpus", m.GetGpus())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("logical_model", m.GetLogicalModel())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("mean_slice_s", m.GetMeanSliceS())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("profile_id", m.GetProfileId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("resident_s", m.GetResidentS())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("slices", m.GetSlices())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("swaps_measured", m.GetSwapsMeasured())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("swap_p50_s", m.GetSwapP50S())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("swap_p90_s", m.GetSwapP90S())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ProfileUtilization) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetGpus sets the gpus property value. The gpus property
func (m *ProfileUtilization) SetGpus(value *int64) {
	m.gpus = value
}

// SetLogicalModel sets the logical_model property value. The logical_model property
func (m *ProfileUtilization) SetLogicalModel(value *string) {
	m.logical_model = value
}

// SetMeanSliceS sets the mean_slice_s property value. The mean_slice_s property
func (m *ProfileUtilization) SetMeanSliceS(value *float64) {
	m.mean_slice_s = value
}

// SetProfileId sets the profile_id property value. The profile_id property
func (m *ProfileUtilization) SetProfileId(value *string) {
	m.profile_id = value
}

// SetResidentS sets the resident_s property value. Seconds a published route existed for the profile inside the window.
func (m *ProfileUtilization) SetResidentS(value *float64) {
	m.resident_s = value
}

// SetSlices sets the slices property value. Route publications inside the window: activations that completed.
func (m *ProfileUtilization) SetSlices(value *int64) {
	m.slices = value
}

// SetSwapP50S sets the swap_p50_s property value. Median seconds the node spent switching before this profile served: its swapcost. Compare against a cold start for the same model.
func (m *ProfileUtilization) SetSwapP50S(value *float64) {
	m.swap_p50_s = value
}

// SetSwapP90S sets the swap_p90_s property value. 90th percentile of the same, so a regression is visible rather than averaged out.
func (m *ProfileUtilization) SetSwapP90S(value *float64) {
	m.swap_p90_s = value
}

// SetSwapsMeasured sets the swaps_measured property value. Swaps into this profile that were measured (the node was empty beforehand).
func (m *ProfileUtilization) SetSwapsMeasured(value *int64) {
	m.swaps_measured = value
}

type ProfileUtilizationable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetGpus() *int64
	GetLogicalModel() *string
	GetMeanSliceS() *float64
	GetProfileId() *string
	GetResidentS() *float64
	GetSlices() *int64
	GetSwapP50S() *float64
	GetSwapP90S() *float64
	GetSwapsMeasured() *int64
	SetGpus(value *int64)
	SetLogicalModel(value *string)
	SetMeanSliceS(value *float64)
	SetProfileId(value *string)
	SetResidentS(value *float64)
	SetSlices(value *int64)
	SetSwapP50S(value *float64)
	SetSwapP90S(value *float64)
	SetSwapsMeasured(value *int64)
}
