// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Residency where a checkpoint currently lives. `node_name` is empty for NFS, which every node shares.
type Residency struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The bytes property
	bytes *int64
	// The node_name property
	node_name *string
	// The since_ms property
	since_ms *int64
	// writing | persisting | copying | present
	state *string
	// The tier property
	tier *string
}

// NewResidency instantiates a new Residency and sets the default values.
func NewResidency() *Residency {
	m := &Residency{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateResidencyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateResidencyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewResidency(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Residency) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetBytes gets the bytes property value. The bytes property
// returns a *int64 when successful
func (m *Residency) GetBytes() *int64 {
	return m.bytes
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *Residency) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["bytes"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetBytes(val)
		}
		return nil
	}
	res["node_name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNodeName(val)
		}
		return nil
	}
	res["since_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSinceMs(val)
		}
		return nil
	}
	res["state"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetState(val)
		}
		return nil
	}
	res["tier"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTier(val)
		}
		return nil
	}
	return res
}

// GetNodeName gets the node_name property value. The node_name property
// returns a *string when successful
func (m *Residency) GetNodeName() *string {
	return m.node_name
}

// GetSinceMs gets the since_ms property value. The since_ms property
// returns a *int64 when successful
func (m *Residency) GetSinceMs() *int64 {
	return m.since_ms
}

// GetState gets the state property value. writing | persisting | copying | present
// returns a *string when successful
func (m *Residency) GetState() *string {
	return m.state
}

// GetTier gets the tier property value. The tier property
// returns a *string when successful
func (m *Residency) GetTier() *string {
	return m.tier
}

// Serialize serializes information the current object
func (m *Residency) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt64Value("bytes", m.GetBytes())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("node_name", m.GetNodeName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("since_ms", m.GetSinceMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("state", m.GetState())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("tier", m.GetTier())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Residency) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetBytes sets the bytes property value. The bytes property
func (m *Residency) SetBytes(value *int64) {
	m.bytes = value
}

// SetNodeName sets the node_name property value. The node_name property
func (m *Residency) SetNodeName(value *string) {
	m.node_name = value
}

// SetSinceMs sets the since_ms property value. The since_ms property
func (m *Residency) SetSinceMs(value *int64) {
	m.since_ms = value
}

// SetState sets the state property value. writing | persisting | copying | present
func (m *Residency) SetState(value *string) {
	m.state = value
}

// SetTier sets the tier property value. The tier property
func (m *Residency) SetTier(value *string) {
	m.tier = value
}

type Residencyable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetBytes() *int64
	GetNodeName() *string
	GetSinceMs() *int64
	GetState() *string
	GetTier() *string
	SetBytes(value *int64)
	SetNodeName(value *string)
	SetSinceMs(value *int64)
	SetState(value *string)
	SetTier(value *string)
}
