// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ResolveResponse struct {
	// The activation_path property
	activation_path *string
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The decision_source property
	decision_source *string
	// The fallback_used property
	fallback_used *bool
	// The lease_duration_ms property
	lease_duration_ms *int64
	// The profile_id property
	profile_id *string
	// The route_generation property
	route_generation *int64
	// The target_name property
	target_name *string
	// The upstream_model property
	upstream_model *string
}

// NewResolveResponse instantiates a new ResolveResponse and sets the default values.
func NewResolveResponse() *ResolveResponse {
	m := &ResolveResponse{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateResolveResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateResolveResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewResolveResponse(), nil
}

// GetActivationPath gets the activation_path property value. The activation_path property
// returns a *string when successful
func (m *ResolveResponse) GetActivationPath() *string {
	return m.activation_path
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ResolveResponse) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetDecisionSource gets the decision_source property value. The decision_source property
// returns a *string when successful
func (m *ResolveResponse) GetDecisionSource() *string {
	return m.decision_source
}

// GetFallbackUsed gets the fallback_used property value. The fallback_used property
// returns a *bool when successful
func (m *ResolveResponse) GetFallbackUsed() *bool {
	return m.fallback_used
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *ResolveResponse) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["activation_path"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetActivationPath(val)
		}
		return nil
	}
	res["decision_source"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDecisionSource(val)
		}
		return nil
	}
	res["fallback_used"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetFallbackUsed(val)
		}
		return nil
	}
	res["lease_duration_ms"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLeaseDurationMs(val)
		}
		return nil
	}
	res["profile_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProfileId(val)
		}
		return nil
	}
	res["route_generation"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRouteGeneration(val)
		}
		return nil
	}
	res["target_name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTargetName(val)
		}
		return nil
	}
	res["upstream_model"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUpstreamModel(val)
		}
		return nil
	}
	return res
}

// GetLeaseDurationMs gets the lease_duration_ms property value. The lease_duration_ms property
// returns a *int64 when successful
func (m *ResolveResponse) GetLeaseDurationMs() *int64 {
	return m.lease_duration_ms
}

// GetProfileId gets the profile_id property value. The profile_id property
// returns a *string when successful
func (m *ResolveResponse) GetProfileId() *string {
	return m.profile_id
}

// GetRouteGeneration gets the route_generation property value. The route_generation property
// returns a *int64 when successful
func (m *ResolveResponse) GetRouteGeneration() *int64 {
	return m.route_generation
}

// GetTargetName gets the target_name property value. The target_name property
// returns a *string when successful
func (m *ResolveResponse) GetTargetName() *string {
	return m.target_name
}

// GetUpstreamModel gets the upstream_model property value. The upstream_model property
// returns a *string when successful
func (m *ResolveResponse) GetUpstreamModel() *string {
	return m.upstream_model
}

// Serialize serializes information the current object
func (m *ResolveResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("activation_path", m.GetActivationPath())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("decision_source", m.GetDecisionSource())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("fallback_used", m.GetFallbackUsed())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("lease_duration_ms", m.GetLeaseDurationMs())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("profile_id", m.GetProfileId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("route_generation", m.GetRouteGeneration())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("target_name", m.GetTargetName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("upstream_model", m.GetUpstreamModel())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetActivationPath sets the activation_path property value. The activation_path property
func (m *ResolveResponse) SetActivationPath(value *string) {
	m.activation_path = value
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ResolveResponse) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetDecisionSource sets the decision_source property value. The decision_source property
func (m *ResolveResponse) SetDecisionSource(value *string) {
	m.decision_source = value
}

// SetFallbackUsed sets the fallback_used property value. The fallback_used property
func (m *ResolveResponse) SetFallbackUsed(value *bool) {
	m.fallback_used = value
}

// SetLeaseDurationMs sets the lease_duration_ms property value. The lease_duration_ms property
func (m *ResolveResponse) SetLeaseDurationMs(value *int64) {
	m.lease_duration_ms = value
}

// SetProfileId sets the profile_id property value. The profile_id property
func (m *ResolveResponse) SetProfileId(value *string) {
	m.profile_id = value
}

// SetRouteGeneration sets the route_generation property value. The route_generation property
func (m *ResolveResponse) SetRouteGeneration(value *int64) {
	m.route_generation = value
}

// SetTargetName sets the target_name property value. The target_name property
func (m *ResolveResponse) SetTargetName(value *string) {
	m.target_name = value
}

// SetUpstreamModel sets the upstream_model property value. The upstream_model property
func (m *ResolveResponse) SetUpstreamModel(value *string) {
	m.upstream_model = value
}

type ResolveResponseable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetActivationPath() *string
	GetDecisionSource() *string
	GetFallbackUsed() *bool
	GetLeaseDurationMs() *int64
	GetProfileId() *string
	GetRouteGeneration() *int64
	GetTargetName() *string
	GetUpstreamModel() *string
	SetActivationPath(value *string)
	SetDecisionSource(value *string)
	SetFallbackUsed(value *bool)
	SetLeaseDurationMs(value *int64)
	SetProfileId(value *string)
	SetRouteGeneration(value *int64)
	SetTargetName(value *string)
	SetUpstreamModel(value *string)
}
