// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// RouterTargetLmcache what the router may assume about a target's LMCache tiers: what wasconfigured (from the profile's template) and whether each tier has everheld anything (from the newest worker's counters). The countersthemselves ride along for display; they change on every scrape and aredeliberately not part of the ETag, so read them as approximate.One caveat the KVBM version did not have: the cache is per node, shared byevery pod on it, so these counters describe the node the newest workerlanded on rather than that worker alone. `node` says which.
type RouterTargetLmcache struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The hit_rate property
	hit_rate *float64
	// The hit_tokens property
	hit_tokens *int64
	// The l1_active property
	l1_active *bool
	// The l1_hit_rate property
	l1_hit_rate *float64
	// The l1_size_gb property
	l1_size_gb *float64
	// The l2_active property
	l2_active *bool
	// The l2_hit_rate property
	l2_hit_rate *float64
	// The l2_size_gb property
	l2_size_gb *float64
	// The node property
	node *string
}

// NewRouterTargetLmcache instantiates a new RouterTargetLmcache and sets the default values.
func NewRouterTargetLmcache() *RouterTargetLmcache {
	m := &RouterTargetLmcache{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateRouterTargetLmcacheFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateRouterTargetLmcacheFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewRouterTargetLmcache(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *RouterTargetLmcache) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *RouterTargetLmcache) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["hit_rate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetHitRate(val)
		}
		return nil
	}
	res["hit_tokens"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetHitTokens(val)
		}
		return nil
	}
	res["l1_active"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetL1Active(val)
		}
		return nil
	}
	res["l1_hit_rate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetL1HitRate(val)
		}
		return nil
	}
	res["l1_size_gb"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetL1SizeGb(val)
		}
		return nil
	}
	res["l2_active"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetL2Active(val)
		}
		return nil
	}
	res["l2_hit_rate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetL2HitRate(val)
		}
		return nil
	}
	res["l2_size_gb"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetL2SizeGb(val)
		}
		return nil
	}
	res["node"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNode(val)
		}
		return nil
	}
	return res
}

// GetHitRate gets the hit_rate property value. The hit_rate property
// returns a *float64 when successful
func (m *RouterTargetLmcache) GetHitRate() *float64 {
	return m.hit_rate
}

// GetHitTokens gets the hit_tokens property value. The hit_tokens property
// returns a *int64 when successful
func (m *RouterTargetLmcache) GetHitTokens() *int64 {
	return m.hit_tokens
}

// GetL1Active gets the l1_active property value. The l1_active property
// returns a *bool when successful
func (m *RouterTargetLmcache) GetL1Active() *bool {
	return m.l1_active
}

// GetL1HitRate gets the l1_hit_rate property value. The l1_hit_rate property
// returns a *float64 when successful
func (m *RouterTargetLmcache) GetL1HitRate() *float64 {
	return m.l1_hit_rate
}

// GetL1SizeGb gets the l1_size_gb property value. The l1_size_gb property
// returns a *float64 when successful
func (m *RouterTargetLmcache) GetL1SizeGb() *float64 {
	return m.l1_size_gb
}

// GetL2Active gets the l2_active property value. The l2_active property
// returns a *bool when successful
func (m *RouterTargetLmcache) GetL2Active() *bool {
	return m.l2_active
}

// GetL2HitRate gets the l2_hit_rate property value. The l2_hit_rate property
// returns a *float64 when successful
func (m *RouterTargetLmcache) GetL2HitRate() *float64 {
	return m.l2_hit_rate
}

// GetL2SizeGb gets the l2_size_gb property value. The l2_size_gb property
// returns a *float64 when successful
func (m *RouterTargetLmcache) GetL2SizeGb() *float64 {
	return m.l2_size_gb
}

// GetNode gets the node property value. The node property
// returns a *string when successful
func (m *RouterTargetLmcache) GetNode() *string {
	return m.node
}

// Serialize serializes information the current object
func (m *RouterTargetLmcache) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteFloat64Value("hit_rate", m.GetHitRate())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("hit_tokens", m.GetHitTokens())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("l1_active", m.GetL1Active())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("l1_hit_rate", m.GetL1HitRate())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("l1_size_gb", m.GetL1SizeGb())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("l2_active", m.GetL2Active())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("l2_hit_rate", m.GetL2HitRate())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("l2_size_gb", m.GetL2SizeGb())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("node", m.GetNode())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *RouterTargetLmcache) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetHitRate sets the hit_rate property value. The hit_rate property
func (m *RouterTargetLmcache) SetHitRate(value *float64) {
	m.hit_rate = value
}

// SetHitTokens sets the hit_tokens property value. The hit_tokens property
func (m *RouterTargetLmcache) SetHitTokens(value *int64) {
	m.hit_tokens = value
}

// SetL1Active sets the l1_active property value. The l1_active property
func (m *RouterTargetLmcache) SetL1Active(value *bool) {
	m.l1_active = value
}

// SetL1HitRate sets the l1_hit_rate property value. The l1_hit_rate property
func (m *RouterTargetLmcache) SetL1HitRate(value *float64) {
	m.l1_hit_rate = value
}

// SetL1SizeGb sets the l1_size_gb property value. The l1_size_gb property
func (m *RouterTargetLmcache) SetL1SizeGb(value *float64) {
	m.l1_size_gb = value
}

// SetL2Active sets the l2_active property value. The l2_active property
func (m *RouterTargetLmcache) SetL2Active(value *bool) {
	m.l2_active = value
}

// SetL2HitRate sets the l2_hit_rate property value. The l2_hit_rate property
func (m *RouterTargetLmcache) SetL2HitRate(value *float64) {
	m.l2_hit_rate = value
}

// SetL2SizeGb sets the l2_size_gb property value. The l2_size_gb property
func (m *RouterTargetLmcache) SetL2SizeGb(value *float64) {
	m.l2_size_gb = value
}

// SetNode sets the node property value. The node property
func (m *RouterTargetLmcache) SetNode(value *string) {
	m.node = value
}

type RouterTargetLmcacheable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetHitRate() *float64
	GetHitTokens() *int64
	GetL1Active() *bool
	GetL1HitRate() *float64
	GetL1SizeGb() *float64
	GetL2Active() *bool
	GetL2HitRate() *float64
	GetL2SizeGb() *float64
	GetNode() *string
	SetHitRate(value *float64)
	SetHitTokens(value *int64)
	SetL1Active(value *bool)
	SetL1HitRate(value *float64)
	SetL1SizeGb(value *float64)
	SetL2Active(value *bool)
	SetL2HitRate(value *float64)
	SetL2SizeGb(value *float64)
	SetNode(value *string)
}
