// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type UtilizationView struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The cluster_id property
	cluster_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
	// Publications by a profile with no restore evidence at all in the window.
	cold_starts *int64
	// The gpu_capacity property
	gpu_capacity *int64
	// gpu_capacity x window, when capacity is known.
	gpu_seconds_available *float64
	// Sum over profiles of resident seconds x GPUs.
	gpu_seconds_resident *float64
	// Seconds in the window during which NO model was serving: the node's dead time,which is the swap cost in aggregate. The number an operator is buying down.
	idle_s *float64
	// The profiles property
	profiles []ProfileUtilizationable
	// Of those, ones a `model.restored` accounts for: the swap was a checkpointrestore, not a cold start. This is the system's central claim, measured.
	restores *int64
	// Activations that completed inside the window (route publications).
	swaps *int64
	// gpu_seconds_resident / gpu_seconds_available; the number to set beside anenterprise fleet's 15-22%. Residency of a serving model, not SM occupancy.
	utilization *float64
	// The window_hours property
	window_hours *float64
}

// NewUtilizationView instantiates a new UtilizationView and sets the default values.
func NewUtilizationView() *UtilizationView {
	m := &UtilizationView{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateUtilizationViewFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateUtilizationViewFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewUtilizationView(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *UtilizationView) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetClusterId gets the cluster_id property value. The cluster_id property
// returns a *UUID when successful
func (m *UtilizationView) GetClusterId() *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID {
	return m.cluster_id
}

// GetColdStarts gets the cold_starts property value. Publications by a profile with no restore evidence at all in the window.
// returns a *int64 when successful
func (m *UtilizationView) GetColdStarts() *int64 {
	return m.cold_starts
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *UtilizationView) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["cluster_id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetUUIDValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetClusterId(val)
		}
		return nil
	}
	res["cold_starts"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetColdStarts(val)
		}
		return nil
	}
	res["gpu_capacity"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetGpuCapacity(val)
		}
		return nil
	}
	res["gpu_seconds_available"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetGpuSecondsAvailable(val)
		}
		return nil
	}
	res["gpu_seconds_resident"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetGpuSecondsResident(val)
		}
		return nil
	}
	res["idle_s"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIdleS(val)
		}
		return nil
	}
	res["profiles"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateProfileUtilizationFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]ProfileUtilizationable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(ProfileUtilizationable)
				}
			}
			m.SetProfiles(res)
		}
		return nil
	}
	res["restores"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRestores(val)
		}
		return nil
	}
	res["swaps"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSwaps(val)
		}
		return nil
	}
	res["utilization"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUtilization(val)
		}
		return nil
	}
	res["window_hours"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetFloat64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetWindowHours(val)
		}
		return nil
	}
	return res
}

// GetGpuCapacity gets the gpu_capacity property value. The gpu_capacity property
// returns a *int64 when successful
func (m *UtilizationView) GetGpuCapacity() *int64 {
	return m.gpu_capacity
}

// GetGpuSecondsAvailable gets the gpu_seconds_available property value. gpu_capacity x window, when capacity is known.
// returns a *float64 when successful
func (m *UtilizationView) GetGpuSecondsAvailable() *float64 {
	return m.gpu_seconds_available
}

// GetGpuSecondsResident gets the gpu_seconds_resident property value. Sum over profiles of resident seconds x GPUs.
// returns a *float64 when successful
func (m *UtilizationView) GetGpuSecondsResident() *float64 {
	return m.gpu_seconds_resident
}

// GetIdleS gets the idle_s property value. Seconds in the window during which NO model was serving: the node's dead time,which is the swap cost in aggregate. The number an operator is buying down.
// returns a *float64 when successful
func (m *UtilizationView) GetIdleS() *float64 {
	return m.idle_s
}

// GetProfiles gets the profiles property value. The profiles property
// returns a []ProfileUtilizationable when successful
func (m *UtilizationView) GetProfiles() []ProfileUtilizationable {
	return m.profiles
}

// GetRestores gets the restores property value. Of those, ones a `model.restored` accounts for: the swap was a checkpointrestore, not a cold start. This is the system's central claim, measured.
// returns a *int64 when successful
func (m *UtilizationView) GetRestores() *int64 {
	return m.restores
}

// GetSwaps gets the swaps property value. Activations that completed inside the window (route publications).
// returns a *int64 when successful
func (m *UtilizationView) GetSwaps() *int64 {
	return m.swaps
}

// GetUtilization gets the utilization property value. gpu_seconds_resident / gpu_seconds_available; the number to set beside anenterprise fleet's 15-22%. Residency of a serving model, not SM occupancy.
// returns a *float64 when successful
func (m *UtilizationView) GetUtilization() *float64 {
	return m.utilization
}

// GetWindowHours gets the window_hours property value. The window_hours property
// returns a *float64 when successful
func (m *UtilizationView) GetWindowHours() *float64 {
	return m.window_hours
}

// Serialize serializes information the current object
func (m *UtilizationView) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteUUIDValue("cluster_id", m.GetClusterId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("cold_starts", m.GetColdStarts())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("gpu_capacity", m.GetGpuCapacity())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("gpu_seconds_available", m.GetGpuSecondsAvailable())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("gpu_seconds_resident", m.GetGpuSecondsResident())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("idle_s", m.GetIdleS())
		if err != nil {
			return err
		}
	}
	if m.GetProfiles() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetProfiles()))
		for i, v := range m.GetProfiles() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("profiles", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("restores", m.GetRestores())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt64Value("swaps", m.GetSwaps())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("utilization", m.GetUtilization())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteFloat64Value("window_hours", m.GetWindowHours())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *UtilizationView) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetClusterId sets the cluster_id property value. The cluster_id property
func (m *UtilizationView) SetClusterId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
	m.cluster_id = value
}

// SetColdStarts sets the cold_starts property value. Publications by a profile with no restore evidence at all in the window.
func (m *UtilizationView) SetColdStarts(value *int64) {
	m.cold_starts = value
}

// SetGpuCapacity sets the gpu_capacity property value. The gpu_capacity property
func (m *UtilizationView) SetGpuCapacity(value *int64) {
	m.gpu_capacity = value
}

// SetGpuSecondsAvailable sets the gpu_seconds_available property value. gpu_capacity x window, when capacity is known.
func (m *UtilizationView) SetGpuSecondsAvailable(value *float64) {
	m.gpu_seconds_available = value
}

// SetGpuSecondsResident sets the gpu_seconds_resident property value. Sum over profiles of resident seconds x GPUs.
func (m *UtilizationView) SetGpuSecondsResident(value *float64) {
	m.gpu_seconds_resident = value
}

// SetIdleS sets the idle_s property value. Seconds in the window during which NO model was serving: the node's dead time,which is the swap cost in aggregate. The number an operator is buying down.
func (m *UtilizationView) SetIdleS(value *float64) {
	m.idle_s = value
}

// SetProfiles sets the profiles property value. The profiles property
func (m *UtilizationView) SetProfiles(value []ProfileUtilizationable) {
	m.profiles = value
}

// SetRestores sets the restores property value. Of those, ones a `model.restored` accounts for: the swap was a checkpointrestore, not a cold start. This is the system's central claim, measured.
func (m *UtilizationView) SetRestores(value *int64) {
	m.restores = value
}

// SetSwaps sets the swaps property value. Activations that completed inside the window (route publications).
func (m *UtilizationView) SetSwaps(value *int64) {
	m.swaps = value
}

// SetUtilization sets the utilization property value. gpu_seconds_resident / gpu_seconds_available; the number to set beside anenterprise fleet's 15-22%. Residency of a serving model, not SM occupancy.
func (m *UtilizationView) SetUtilization(value *float64) {
	m.utilization = value
}

// SetWindowHours sets the window_hours property value. The window_hours property
func (m *UtilizationView) SetWindowHours(value *float64) {
	m.window_hours = value
}

type UtilizationViewable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetClusterId() *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
	GetColdStarts() *int64
	GetGpuCapacity() *int64
	GetGpuSecondsAvailable() *float64
	GetGpuSecondsResident() *float64
	GetIdleS() *float64
	GetProfiles() []ProfileUtilizationable
	GetRestores() *int64
	GetSwaps() *int64
	GetUtilization() *float64
	GetWindowHours() *float64
	SetClusterId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
	SetColdStarts(value *int64)
	SetGpuCapacity(value *int64)
	SetGpuSecondsAvailable(value *float64)
	SetGpuSecondsResident(value *float64)
	SetIdleS(value *float64)
	SetProfiles(value []ProfileUtilizationable)
	SetRestores(value *int64)
	SetSwaps(value *int64)
	SetUtilization(value *float64)
	SetWindowHours(value *float64)
}
