// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89 "github.com/cedana/cedana-propagator-sdk/go/models"
	i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// CheckpointsRequestBuilder builds and executes requests for operations under \v1\checkpoints
type CheckpointsRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// CheckpointsRequestBuilderGetQueryParameters paginated. `ids` (comma-separated UUIDs) and `cluster_id` (the cluster the checkpoint actionran on) filter the list; `total_count` is the number of matches before paging.
type CheckpointsRequestBuilderGetQueryParameters struct {
	// Sort ascending (default false)
	Ascending *bool "uriparametername:\"ascending\""
	// Only return checkpoints whose checkpoint action ran on this cluster
	Cluster_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID "uriparametername:\"cluster_id\""
	// Comma-separated list of checkpoint UUIDs to filter by
	Ids *string "uriparametername:\"ids\""
	// Page size (default 50, max 500)
	Limit *int64 "uriparametername:\"limit\""
	// Row offset (default 0)
	Offset *int64 "uriparametername:\"offset\""
	// Sort column: `id`, `name`, `status`, `platform` or `gpu` (default `id`)
	Sort *string "uriparametername:\"sort\""
}

// CheckpointsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CheckpointsRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
	// Request query parameters
	QueryParameters *CheckpointsRequestBuilderGetQueryParameters
}

// CheckpointsRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CheckpointsRequestBuilderPostRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}

// ById gets an item from the github.com/cedana/cedana-propagator-sdk/go.v1.checkpoints.item collection
// returns a *CheckpointsCheckpointsItemRequestBuilder when successful
func (m *CheckpointsRequestBuilder) ById(id string) *CheckpointsCheckpointsItemRequestBuilder {
	urlTplParams := make(map[string]string)
	for idx, item := range m.BaseRequestBuilder.PathParameters {
		urlTplParams[idx] = item
	}
	if id != "" {
		urlTplParams["id"] = id
	}
	return NewCheckpointsCheckpointsItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}

// NewCheckpointsRequestBuilderInternal instantiates a new CheckpointsRequestBuilder and sets the default values.
func NewCheckpointsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *CheckpointsRequestBuilder {
	m := &CheckpointsRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/checkpoints{?ascending*,cluster_id*,ids*,limit*,offset*,sort*}", pathParameters),
	}
	return m
}

// NewCheckpointsRequestBuilder instantiates a new CheckpointsRequestBuilder and sets the default values.
func NewCheckpointsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *CheckpointsRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewCheckpointsRequestBuilderInternal(urlParams, requestAdapter)
}

// Deprecate the deprecate property
// returns a *CheckpointsDeprecateRequestBuilder when successful
func (m *CheckpointsRequestBuilder) Deprecate() *CheckpointsDeprecateRequestBuilder {
	return NewCheckpointsDeprecateRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Get paginated. `ids` (comma-separated UUIDs) and `cluster_id` (the cluster the checkpoint actionran on) filter the list; `total_count` is the number of matches before paging.
// returns a PaginatedCheckpointResponseable when successful
// returns a HttpError error when the service returns a 400 status code
// returns a HttpError error when the service returns a 500 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *CheckpointsRequestBuilder) Get(ctx context.Context, requestConfiguration *CheckpointsRequestBuilderGetRequestConfiguration) (i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.PaginatedCheckpointResponseable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"500": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreatePaginatedCheckpointResponseFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.PaginatedCheckpointResponseable), nil
}

// Info the info property
// returns a *CheckpointsInfoRequestBuilder when successful
func (m *CheckpointsRequestBuilder) Info() *CheckpointsInfoRequestBuilder {
	return NewCheckpointsInfoRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Post builds a new checkpoint without the metadata and information about the checkpoint with status initializing
// returns a *string when successful
// returns a HttpError error when the service returns a 500 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *CheckpointsRequestBuilder) Post(ctx context.Context, requestConfiguration *CheckpointsRequestBuilderPostRequestConfiguration) (*string, error) {
	requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"500": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendPrimitive(ctx, requestInfo, "string", errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(*string), nil
}

// ToGetRequestInformation paginated. `ids` (comma-separated UUIDs) and `cluster_id` (the cluster the checkpoint actionran on) filter the list; `total_count` is the number of matches before paging.
// returns a *RequestInformation when successful
func (m *CheckpointsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *CheckpointsRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		if requestConfiguration.QueryParameters != nil {
			requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
		}
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// ToPostRequestInformation builds a new checkpoint without the metadata and information about the checkpoint with status initializing
// returns a *RequestInformation when successful
func (m *CheckpointsRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *CheckpointsRequestBuilderPostRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9")
	return requestInfo, nil
}

// Uploaded the uploaded property
// returns a *CheckpointsUploadedRequestBuilder when successful
func (m *CheckpointsRequestBuilder) Uploaded() *CheckpointsUploadedRequestBuilder {
	return NewCheckpointsUploadedRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CheckpointsRequestBuilder when successful
func (m *CheckpointsRequestBuilder) WithUrl(rawUrl string) *CheckpointsRequestBuilder {
	return NewCheckpointsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
