// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89 "github.com/cedana/cedana-propagator-sdk/go/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// CheckpointsItemStorageRequestBuilder builds and executes requests for operations under \v1\checkpoints\{id}\storage
type CheckpointsItemStorageRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// CheckpointsItemStorageRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CheckpointsItemStorageRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}

// NewCheckpointsItemStorageRequestBuilderInternal instantiates a new CheckpointsItemStorageRequestBuilder and sets the default values.
func NewCheckpointsItemStorageRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *CheckpointsItemStorageRequestBuilder {
	m := &CheckpointsItemStorageRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/checkpoints/{id}/storage", pathParameters),
	}
	return m
}

// NewCheckpointsItemStorageRequestBuilder instantiates a new CheckpointsItemStorageRequestBuilder and sets the default values.
func NewCheckpointsItemStorageRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *CheckpointsItemStorageRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewCheckpointsItemStorageRequestBuilderInternal(urlParams, requestAdapter)
}

// Get storage timeline and current residency of a CSX checkpoint
// returns a CheckpointStorageable when successful
// returns a HttpError error when the service returns a 400 status code
// returns a HttpError error when the service returns a 503 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *CheckpointsItemStorageRequestBuilder) Get(ctx context.Context, requestConfiguration *CheckpointsItemStorageRequestBuilderGetRequestConfiguration) (i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CheckpointStorageable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"503": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateCheckpointStorageFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CheckpointStorageable), nil
}

// ToGetRequestInformation storage timeline and current residency of a CSX checkpoint
// returns a *RequestInformation when successful
func (m *CheckpointsItemStorageRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *CheckpointsItemStorageRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CheckpointsItemStorageRequestBuilder when successful
func (m *CheckpointsItemStorageRequestBuilder) WithUrl(rawUrl string) *CheckpointsItemStorageRequestBuilder {
	return NewCheckpointsItemStorageRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
