// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89 "github.com/cedana/cedana-propagator-sdk/go/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// CheckpointsItemFilesRequestBuilder builds and executes requests for operations under \v1\checkpoints\{id}\files
type CheckpointsItemFilesRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// CheckpointsItemFilesRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CheckpointsItemFilesRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}

// NewCheckpointsItemFilesRequestBuilderInternal instantiates a new CheckpointsItemFilesRequestBuilder and sets the default values.
func NewCheckpointsItemFilesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *CheckpointsItemFilesRequestBuilder {
	m := &CheckpointsItemFilesRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/checkpoints/{id}/files", pathParameters),
	}
	return m
}

// NewCheckpointsItemFilesRequestBuilder instantiates a new CheckpointsItemFilesRequestBuilder and sets the default values.
func NewCheckpointsItemFilesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *CheckpointsItemFilesRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewCheckpointsItemFilesRequestBuilderInternal(urlParams, requestAdapter)
}

// Download the download property
// returns a *CheckpointsItemFilesDownloadRequestBuilder when successful
func (m *CheckpointsItemFilesRequestBuilder) Download() *CheckpointsItemFilesDownloadRequestBuilder {
	return NewCheckpointsItemFilesDownloadRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Get asks a helper on the checkpoint's cluster to read the checkpoint and returns the filesinside it (the members of the checkpoint archive).
// returns a []CheckpointFileEntryable when successful
// returns a HttpError error when the service returns a 400 status code
// returns a HttpError error when the service returns a 404 status code
// returns a HttpError error when the service returns a 409 status code
// returns a HttpError error when the service returns a 502 status code
// returns a HttpError error when the service returns a 504 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *CheckpointsItemFilesRequestBuilder) Get(ctx context.Context, requestConfiguration *CheckpointsItemFilesRequestBuilderGetRequestConfiguration) ([]i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CheckpointFileEntryable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"404": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"409": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"502": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"504": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateCheckpointFileEntryFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	val := make([]i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CheckpointFileEntryable, len(res))
	for i, v := range res {
		if v != nil {
			val[i] = v.(i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CheckpointFileEntryable)
		}
	}
	return val, nil
}

// ToGetRequestInformation asks a helper on the checkpoint's cluster to read the checkpoint and returns the filesinside it (the members of the checkpoint archive).
// returns a *RequestInformation when successful
func (m *CheckpointsItemFilesRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *CheckpointsItemFilesRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CheckpointsItemFilesRequestBuilder when successful
func (m *CheckpointsItemFilesRequestBuilder) WithUrl(rawUrl string) *CheckpointsItemFilesRequestBuilder {
	return NewCheckpointsItemFilesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
