// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89 "github.com/cedana/cedana-propagator-sdk/go/models"
	i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// DynamoCheckpointsRequestBuilder builds and executes requests for operations under \v1\dynamo\checkpoints
type DynamoCheckpointsRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// DynamoCheckpointsRequestBuilderGetQueryParameters returns checkpoints in the given cluster, optionally filtered byCEDANA_CHECKPOINT name. Each entry is a reusable warm-state asset that anydeployment with a matching CEDANA_CHECKPOINT env restores from.
type DynamoCheckpointsRequestBuilderGetQueryParameters struct {
	// Cluster to scope checkpoints to.
	Cluster_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID "uriparametername:\"cluster_id\""
	// Optional CEDANA_CHECKPOINT name to filter by
	Name *string "uriparametername:\"name\""
}

// DynamoCheckpointsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type DynamoCheckpointsRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
	// Request query parameters
	QueryParameters *DynamoCheckpointsRequestBuilderGetQueryParameters
}

// NewDynamoCheckpointsRequestBuilderInternal instantiates a new DynamoCheckpointsRequestBuilder and sets the default values.
func NewDynamoCheckpointsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *DynamoCheckpointsRequestBuilder {
	m := &DynamoCheckpointsRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/dynamo/checkpoints?cluster_id={cluster_id}{&name*}", pathParameters),
	}
	return m
}

// NewDynamoCheckpointsRequestBuilder instantiates a new DynamoCheckpointsRequestBuilder and sets the default values.
func NewDynamoCheckpointsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *DynamoCheckpointsRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewDynamoCheckpointsRequestBuilderInternal(urlParams, requestAdapter)
}

// Get returns checkpoints in the given cluster, optionally filtered byCEDANA_CHECKPOINT name. Each entry is a reusable warm-state asset that anydeployment with a matching CEDANA_CHECKPOINT env restores from.
// returns a []DynamoCheckpointEntryable when successful
// returns a HttpError error when the service returns a 500 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *DynamoCheckpointsRequestBuilder) Get(ctx context.Context, requestConfiguration *DynamoCheckpointsRequestBuilderGetRequestConfiguration) ([]i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.DynamoCheckpointEntryable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"500": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateDynamoCheckpointEntryFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	val := make([]i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.DynamoCheckpointEntryable, len(res))
	for i, v := range res {
		if v != nil {
			val[i] = v.(i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.DynamoCheckpointEntryable)
		}
	}
	return val, nil
}

// ToGetRequestInformation returns checkpoints in the given cluster, optionally filtered byCEDANA_CHECKPOINT name. Each entry is a reusable warm-state asset that anydeployment with a matching CEDANA_CHECKPOINT env restores from.
// returns a *RequestInformation when successful
func (m *DynamoCheckpointsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *DynamoCheckpointsRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		if requestConfiguration.QueryParameters != nil {
			requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
		}
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *DynamoCheckpointsRequestBuilder when successful
func (m *DynamoCheckpointsRequestBuilder) WithUrl(rawUrl string) *DynamoCheckpointsRequestBuilder {
	return NewDynamoCheckpointsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
