// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// InferenceProfilesItemLmcacheRequestBuilder builds and executes requests for operations under \v1\inference\profiles\{profile_id}\lmcache
type InferenceProfilesItemLmcacheRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewInferenceProfilesItemLmcacheRequestBuilderInternal instantiates a new InferenceProfilesItemLmcacheRequestBuilder and sets the default values.
func NewInferenceProfilesItemLmcacheRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InferenceProfilesItemLmcacheRequestBuilder {
	m := &InferenceProfilesItemLmcacheRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/inference/profiles/{profile_id}/lmcache", pathParameters),
	}
	return m
}

// NewInferenceProfilesItemLmcacheRequestBuilder instantiates a new InferenceProfilesItemLmcacheRequestBuilder and sets the default values.
func NewInferenceProfilesItemLmcacheRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InferenceProfilesItemLmcacheRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewInferenceProfilesItemLmcacheRequestBuilderInternal(urlParams, requestAdapter)
}

// Series the series property
// returns a *InferenceProfilesItemLmcacheSeriesRequestBuilder when successful
func (m *InferenceProfilesItemLmcacheRequestBuilder) Series() *InferenceProfilesItemLmcacheSeriesRequestBuilder {
	return NewInferenceProfilesItemLmcacheSeriesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
