// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// InferenceProfilesItemKvbmRequestBuilder builds and executes requests for operations under \v1\inference\profiles\{profile_id}\kvbm
type InferenceProfilesItemKvbmRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewInferenceProfilesItemKvbmRequestBuilderInternal instantiates a new InferenceProfilesItemKvbmRequestBuilder and sets the default values.
func NewInferenceProfilesItemKvbmRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InferenceProfilesItemKvbmRequestBuilder {
	m := &InferenceProfilesItemKvbmRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/inference/profiles/{profile_id}/kvbm", pathParameters),
	}
	return m
}

// NewInferenceProfilesItemKvbmRequestBuilder instantiates a new InferenceProfilesItemKvbmRequestBuilder and sets the default values.
func NewInferenceProfilesItemKvbmRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InferenceProfilesItemKvbmRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewInferenceProfilesItemKvbmRequestBuilderInternal(urlParams, requestAdapter)
}

// Series the series property
// returns a *InferenceProfilesItemKvbmSeriesRequestBuilder when successful
func (m *InferenceProfilesItemKvbmRequestBuilder) Series() *InferenceProfilesItemKvbmSeriesRequestBuilder {
	return NewInferenceProfilesItemKvbmSeriesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
