// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89 "github.com/cedana/cedana-propagator-sdk/go/models"
	i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
)

// InferenceHistoryWithStreamItemRequestBuilder builds and executes requests for operations under \v1\inference\history\{stream}
type InferenceHistoryWithStreamItemRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// InferenceHistoryWithStreamItemRequestBuilderGetQueryParameters replays lifecycle, placement, or request records in stable timestamp/id order,falling back to ingestion time. Late arrivals can precede a cursor: re-exportafter telemetry drains.
type InferenceHistoryWithStreamItemRequestBuilderGetQueryParameters struct {
	After_id   *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID "uriparametername:\"after_id\""
	After_time *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time "uriparametername:\"after_time\""
	// Applicable to lifecycle and placement; requests have no cluster identity.
	Cluster_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID "uriparametername:\"cluster_id\""
	Limit      *int64                                                                  "uriparametername:\"limit\""
	Profile_id *string                                                                 "uriparametername:\"profile_id\""
	Since      *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time "uriparametername:\"since\""
	// Exclusive end of the recording window. Keep fixed while paging.
	Until *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time "uriparametername:\"until\""
}

// InferenceHistoryWithStreamItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type InferenceHistoryWithStreamItemRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
	// Request query parameters
	QueryParameters *InferenceHistoryWithStreamItemRequestBuilderGetQueryParameters
}

// NewInferenceHistoryWithStreamItemRequestBuilderInternal instantiates a new InferenceHistoryWithStreamItemRequestBuilder and sets the default values.
func NewInferenceHistoryWithStreamItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InferenceHistoryWithStreamItemRequestBuilder {
	m := &InferenceHistoryWithStreamItemRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/inference/history/{stream}?since={since}&until={until}{&after_id*,after_time*,cluster_id*,limit*,profile_id*}", pathParameters),
	}
	return m
}

// NewInferenceHistoryWithStreamItemRequestBuilder instantiates a new InferenceHistoryWithStreamItemRequestBuilder and sets the default values.
func NewInferenceHistoryWithStreamItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InferenceHistoryWithStreamItemRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewInferenceHistoryWithStreamItemRequestBuilderInternal(urlParams, requestAdapter)
}

// Get replays lifecycle, placement, or request records in stable timestamp/id order,falling back to ingestion time. Late arrivals can precede a cursor: re-exportafter telemetry drains.
// returns a HistoryPageable when successful
// returns a HttpError error when the service returns a 400 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *InferenceHistoryWithStreamItemRequestBuilder) Get(ctx context.Context, requestConfiguration *InferenceHistoryWithStreamItemRequestBuilderGetRequestConfiguration) (i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.HistoryPageable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHistoryPageFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.HistoryPageable), nil
}

// ToGetRequestInformation replays lifecycle, placement, or request records in stable timestamp/id order,falling back to ingestion time. Late arrivals can precede a cursor: re-exportafter telemetry drains.
// returns a *RequestInformation when successful
func (m *InferenceHistoryWithStreamItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *InferenceHistoryWithStreamItemRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		if requestConfiguration.QueryParameters != nil {
			requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
		}
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *InferenceHistoryWithStreamItemRequestBuilder when successful
func (m *InferenceHistoryWithStreamItemRequestBuilder) WithUrl(rawUrl string) *InferenceHistoryWithStreamItemRequestBuilder {
	return NewInferenceHistoryWithStreamItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
