// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89 "github.com/cedana/cedana-propagator-sdk/go/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// InferenceProfilesItemKvbmSeriesRequestBuilder builds and executes requests for operations under \v1\inference\profiles\{profile_id}\kvbm\series
type InferenceProfilesItemKvbmSeriesRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// InferenceProfilesItemKvbmSeriesRequestBuilderGetQueryParameters kVBM was replaced by LMCache MP; this path answers identically so a UIimage rolled ahead of, or behind, the propagator keeps working. Remove itone release after the UI stops calling it.
type InferenceProfilesItemKvbmSeriesRequestBuilderGetQueryParameters struct {
	// Bucket width; 0 for raw samples
	Bucket_seconds *int64 "uriparametername:\"bucket_seconds\""
	// Window in minutes (default 60)
	Minutes *int64 "uriparametername:\"minutes\""
}

// InferenceProfilesItemKvbmSeriesRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type InferenceProfilesItemKvbmSeriesRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
	// Request query parameters
	QueryParameters *InferenceProfilesItemKvbmSeriesRequestBuilderGetQueryParameters
}

// NewInferenceProfilesItemKvbmSeriesRequestBuilderInternal instantiates a new InferenceProfilesItemKvbmSeriesRequestBuilder and sets the default values.
func NewInferenceProfilesItemKvbmSeriesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InferenceProfilesItemKvbmSeriesRequestBuilder {
	m := &InferenceProfilesItemKvbmSeriesRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/inference/profiles/{profile_id}/kvbm/series{?bucket_seconds*,minutes*}", pathParameters),
	}
	return m
}

// NewInferenceProfilesItemKvbmSeriesRequestBuilder instantiates a new InferenceProfilesItemKvbmSeriesRequestBuilder and sets the default values.
func NewInferenceProfilesItemKvbmSeriesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InferenceProfilesItemKvbmSeriesRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewInferenceProfilesItemKvbmSeriesRequestBuilderInternal(urlParams, requestAdapter)
}

// Get kVBM was replaced by LMCache MP; this path answers identically so a UIimage rolled ahead of, or behind, the propagator keeps working. Remove itone release after the UI stops calling it.
// returns a LmcacheSeriesResponseable when successful
// returns a HttpError error when the service returns a 400 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *InferenceProfilesItemKvbmSeriesRequestBuilder) Get(ctx context.Context, requestConfiguration *InferenceProfilesItemKvbmSeriesRequestBuilderGetRequestConfiguration) (i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.LmcacheSeriesResponseable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateLmcacheSeriesResponseFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.LmcacheSeriesResponseable), nil
}

// ToGetRequestInformation kVBM was replaced by LMCache MP; this path answers identically so a UIimage rolled ahead of, or behind, the propagator keeps working. Remove itone release after the UI stops calling it.
// returns a *RequestInformation when successful
func (m *InferenceProfilesItemKvbmSeriesRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *InferenceProfilesItemKvbmSeriesRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		if requestConfiguration.QueryParameters != nil {
			requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
		}
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *InferenceProfilesItemKvbmSeriesRequestBuilder when successful
func (m *InferenceProfilesItemKvbmSeriesRequestBuilder) WithUrl(rawUrl string) *InferenceProfilesItemKvbmSeriesRequestBuilder {
	return NewInferenceProfilesItemKvbmSeriesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
