// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89 "github.com/cedana/cedana-propagator-sdk/go/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// InferenceProfilesItemRestoreHintsRequestBuilder builds and executes requests for operations under \v1\inference\profiles\{profile_id}\restore-hints
type InferenceProfilesItemRestoreHintsRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// InferenceProfilesItemRestoreHintsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type InferenceProfilesItemRestoreHintsRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}

// NewInferenceProfilesItemRestoreHintsRequestBuilderInternal instantiates a new InferenceProfilesItemRestoreHintsRequestBuilder and sets the default values.
func NewInferenceProfilesItemRestoreHintsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InferenceProfilesItemRestoreHintsRequestBuilder {
	m := &InferenceProfilesItemRestoreHintsRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/inference/profiles/{profile_id}/restore-hints", pathParameters),
	}
	return m
}

// NewInferenceProfilesItemRestoreHintsRequestBuilder instantiates a new InferenceProfilesItemRestoreHintsRequestBuilder and sets the default values.
func NewInferenceProfilesItemRestoreHintsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InferenceProfilesItemRestoreHintsRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewInferenceProfilesItemRestoreHintsRequestBuilderInternal(urlParams, requestAdapter)
}

// Get read at artifact-selection time: a checkpoint whose resident conversationsintersect these hints saves the parked requests their prefill. Rows arebounded and pruned on write; staleness is the reader's judgment, which iswhy last_seen is part of every row.
// returns a []PrefixHintViewable when successful
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *InferenceProfilesItemRestoreHintsRequestBuilder) Get(ctx context.Context, requestConfiguration *InferenceProfilesItemRestoreHintsRequestBuilderGetRequestConfiguration) ([]i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.PrefixHintViewable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreatePrefixHintViewFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	val := make([]i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.PrefixHintViewable, len(res))
	for i, v := range res {
		if v != nil {
			val[i] = v.(i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.PrefixHintViewable)
		}
	}
	return val, nil
}

// ToGetRequestInformation read at artifact-selection time: a checkpoint whose resident conversationsintersect these hints saves the parked requests their prefill. Rows arebounded and pruned on write; staleness is the reader's judgment, which iswhy last_seen is part of every row.
// returns a *RequestInformation when successful
func (m *InferenceProfilesItemRestoreHintsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *InferenceProfilesItemRestoreHintsRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *InferenceProfilesItemRestoreHintsRequestBuilder when successful
func (m *InferenceProfilesItemRestoreHintsRequestBuilder) WithUrl(rawUrl string) *InferenceProfilesItemRestoreHintsRequestBuilder {
	return NewInferenceProfilesItemRestoreHintsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
