// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89 "github.com/cedana/cedana-propagator-sdk/go/models"
	i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// JobsByPriorityWithPriorityItemRequestBuilder builds and executes requests for operations under \v1\jobs\by-priority\{priority}
type JobsByPriorityWithPriorityItemRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

type JobsByPriorityWithPriorityItemRequestBuilderGetQueryParameters struct {
	// Only consider resources belonging to this cluster
	Cluster_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID "uriparametername:\"cluster_id\""
}

// JobsByPriorityWithPriorityItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type JobsByPriorityWithPriorityItemRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
	// Request query parameters
	QueryParameters *JobsByPriorityWithPriorityItemRequestBuilderGetQueryParameters
}

// NewJobsByPriorityWithPriorityItemRequestBuilderInternal instantiates a new JobsByPriorityWithPriorityItemRequestBuilder and sets the default values.
func NewJobsByPriorityWithPriorityItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *JobsByPriorityWithPriorityItemRequestBuilder {
	m := &JobsByPriorityWithPriorityItemRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/jobs/by-priority/{priority}{?cluster_id*}", pathParameters),
	}
	return m
}

// NewJobsByPriorityWithPriorityItemRequestBuilder instantiates a new JobsByPriorityWithPriorityItemRequestBuilder and sets the default values.
func NewJobsByPriorityWithPriorityItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *JobsByPriorityWithPriorityItemRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewJobsByPriorityWithPriorityItemRequestBuilderInternal(urlParams, requestAdapter)
}

// returns a PaginatedJobResponseable when successful
// returns a HttpError error when the service returns a 500 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *JobsByPriorityWithPriorityItemRequestBuilder) Get(ctx context.Context, requestConfiguration *JobsByPriorityWithPriorityItemRequestBuilderGetRequestConfiguration) (i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.PaginatedJobResponseable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"500": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreatePaginatedJobResponseFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.PaginatedJobResponseable), nil
}

// returns a *RequestInformation when successful
func (m *JobsByPriorityWithPriorityItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *JobsByPriorityWithPriorityItemRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		if requestConfiguration.QueryParameters != nil {
			requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
		}
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *JobsByPriorityWithPriorityItemRequestBuilder when successful
func (m *JobsByPriorityWithPriorityItemRequestBuilder) WithUrl(rawUrl string) *JobsByPriorityWithPriorityItemRequestBuilder {
	return NewJobsByPriorityWithPriorityItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
