// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89 "github.com/cedana/cedana-propagator-sdk/go/models"
	i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// NodesRequestBuilder builds and executes requests for operations under \v1\nodes
type NodesRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NodesRequestBuilderGetQueryParameters will only return nodes from clusters with status 'active' if no params are provided. Also, nodeswith last_sync older than 5 minutes are not returned.
type NodesRequestBuilderGetQueryParameters struct {
	// Only return nodes belonging to this cluster
	Cluster_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID "uriparametername:\"cluster_id\""
	Id         *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID "uriparametername:\"id\""
}

// NodesRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type NodesRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
	// Request query parameters
	QueryParameters *NodesRequestBuilderGetQueryParameters
}

// NewNodesRequestBuilderInternal instantiates a new NodesRequestBuilder and sets the default values.
func NewNodesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *NodesRequestBuilder {
	m := &NodesRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/nodes{?cluster_id*,id*}", pathParameters),
	}
	return m
}

// NewNodesRequestBuilder instantiates a new NodesRequestBuilder and sets the default values.
func NewNodesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *NodesRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewNodesRequestBuilderInternal(urlParams, requestAdapter)
}

// Count the count property
// returns a *NodesCountRequestBuilder when successful
func (m *NodesRequestBuilder) Count() *NodesCountRequestBuilder {
	return NewNodesCountRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Get will only return nodes from clusters with status 'active' if no params are provided. Also, nodeswith last_sync older than 5 minutes are not returned.
// returns a []NodeResponseable when successful
// returns a HttpError error when the service returns a 500 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *NodesRequestBuilder) Get(ctx context.Context, requestConfiguration *NodesRequestBuilderGetRequestConfiguration) ([]i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.NodeResponseable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"500": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateNodeResponseFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	val := make([]i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.NodeResponseable, len(res))
	for i, v := range res {
		if v != nil {
			val[i] = v.(i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.NodeResponseable)
		}
	}
	return val, nil
}

// ToGetRequestInformation will only return nodes from clusters with status 'active' if no params are provided. Also, nodeswith last_sync older than 5 minutes are not returned.
// returns a *RequestInformation when successful
func (m *NodesRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *NodesRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		if requestConfiguration.QueryParameters != nil {
			requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
		}
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *NodesRequestBuilder when successful
func (m *NodesRequestBuilder) WithUrl(rawUrl string) *NodesRequestBuilder {
	return NewNodesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
