// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89 "github.com/cedana/cedana-propagator-sdk/go/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// SlurmClustersRequestBuilder builds and executes requests for operations under \v1\slurm\clusters
type SlurmClustersRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// SlurmClustersRequestBuilderGetQueryParameters paginated. `total_count` is the number of SLURM clusters before paging.
type SlurmClustersRequestBuilderGetQueryParameters struct {
	// Page size (default 50, max 500)
	Limit *int64 "uriparametername:\"limit\""
	// Row offset (default 0)
	Offset *int64 "uriparametername:\"offset\""
}

// SlurmClustersRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SlurmClustersRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
	// Request query parameters
	QueryParameters *SlurmClustersRequestBuilderGetQueryParameters
}

// NewSlurmClustersRequestBuilderInternal instantiates a new SlurmClustersRequestBuilder and sets the default values.
func NewSlurmClustersRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *SlurmClustersRequestBuilder {
	m := &SlurmClustersRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/slurm/clusters{?limit*,offset*}", pathParameters),
	}
	return m
}

// NewSlurmClustersRequestBuilder instantiates a new SlurmClustersRequestBuilder and sets the default values.
func NewSlurmClustersRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *SlurmClustersRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewSlurmClustersRequestBuilderInternal(urlParams, requestAdapter)
}

// Get paginated. `total_count` is the number of SLURM clusters before paging.
// returns a PaginatedSlurmClusterResponseable when successful
// returns a HttpError error when the service returns a 400 status code
// returns a HttpError error when the service returns a 500 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *SlurmClustersRequestBuilder) Get(ctx context.Context, requestConfiguration *SlurmClustersRequestBuilderGetRequestConfiguration) (i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.PaginatedSlurmClusterResponseable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"500": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreatePaginatedSlurmClusterResponseFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.PaginatedSlurmClusterResponseable), nil
}

// Sync the sync property
// returns a *SlurmClustersSyncRequestBuilder when successful
func (m *SlurmClustersRequestBuilder) Sync() *SlurmClustersSyncRequestBuilder {
	return NewSlurmClustersSyncRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// ToGetRequestInformation paginated. `total_count` is the number of SLURM clusters before paging.
// returns a *RequestInformation when successful
func (m *SlurmClustersRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *SlurmClustersRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		if requestConfiguration.QueryParameters != nil {
			requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
		}
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *SlurmClustersRequestBuilder when successful
func (m *SlurmClustersRequestBuilder) WithUrl(rawUrl string) *SlurmClustersRequestBuilder {
	return NewSlurmClustersRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
