// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"
	i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89 "github.com/cedana/cedana-propagator-sdk/go/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// SlurmMaintenance_windowRequestBuilder builds and executes requests for operations under \v1\slurm\maintenance_window
type SlurmMaintenance_windowRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// SlurmMaintenance_windowRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SlurmMaintenance_windowRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}

// SlurmMaintenance_windowRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SlurmMaintenance_windowRequestBuilderPostRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}

// ById gets an item from the github.com/cedana/cedana-propagator-sdk/go.v1.slurm.maintenance_window.item collection
// returns a *SlurmMaintenance_windowMaintenance_windowItemRequestBuilder when successful
func (m *SlurmMaintenance_windowRequestBuilder) ById(id string) *SlurmMaintenance_windowMaintenance_windowItemRequestBuilder {
	urlTplParams := make(map[string]string)
	for idx, item := range m.BaseRequestBuilder.PathParameters {
		urlTplParams[idx] = item
	}
	if id != "" {
		urlTplParams["id"] = id
	}
	return NewSlurmMaintenance_windowMaintenance_windowItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}

// NewSlurmMaintenance_windowRequestBuilderInternal instantiates a new SlurmMaintenance_windowRequestBuilder and sets the default values.
func NewSlurmMaintenance_windowRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *SlurmMaintenance_windowRequestBuilder {
	m := &SlurmMaintenance_windowRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/slurm/maintenance_window", pathParameters),
	}
	return m
}

// NewSlurmMaintenance_windowRequestBuilder instantiates a new SlurmMaintenance_windowRequestBuilder and sets the default values.
func NewSlurmMaintenance_windowRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *SlurmMaintenance_windowRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewSlurmMaintenance_windowRequestBuilderInternal(urlParams, requestAdapter)
}

// Get returns all maintenance windows
// returns a []SlurmMaintenanceWindowable when successful
// returns a HttpError error when the service returns a 500 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *SlurmMaintenance_windowRequestBuilder) Get(ctx context.Context, requestConfiguration *SlurmMaintenance_windowRequestBuilderGetRequestConfiguration) ([]i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.SlurmMaintenanceWindowable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"500": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateSlurmMaintenanceWindowFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	val := make([]i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.SlurmMaintenanceWindowable, len(res))
	for i, v := range res {
		if v != nil {
			val[i] = v.(i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.SlurmMaintenanceWindowable)
		}
	}
	return val, nil
}

// Post creates a new maintenance window for SLURM clusters
// returns a *string when successful
// returns a HttpError error when the service returns a 400 status code
// returns a HttpError error when the service returns a 500 status code
// returns a HttpError error when the service returns a 4XX or 5XX status code
func (m *SlurmMaintenance_windowRequestBuilder) Post(ctx context.Context, body i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateMaintenanceWindowable, requestConfiguration *SlurmMaintenance_windowRequestBuilderPostRequestConfiguration) (*string, error) {
	requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"500": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
		"XXX": i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateHttpErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendPrimitive(ctx, requestInfo, "string", errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(*string), nil
}

// Sync the sync property
// returns a *SlurmMaintenance_windowSyncRequestBuilder when successful
func (m *SlurmMaintenance_windowRequestBuilder) Sync() *SlurmMaintenance_windowSyncRequestBuilder {
	return NewSlurmMaintenance_windowSyncRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// ToGetRequestInformation returns all maintenance windows
// returns a *RequestInformation when successful
func (m *SlurmMaintenance_windowRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *SlurmMaintenance_windowRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// ToPostRequestInformation creates a new maintenance window for SLURM clusters
// returns a *RequestInformation when successful
func (m *SlurmMaintenance_windowRequestBuilder) ToPostRequestInformation(ctx context.Context, body i89856fb30cc728ac649e5f2184f35b3dbca9c394c0e717f9e3ad3070b5506e89.CreateMaintenanceWindowable, requestConfiguration *SlurmMaintenance_windowRequestBuilderPostRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9")
	err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
	if err != nil {
		return nil, err
	}
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *SlurmMaintenance_windowRequestBuilder when successful
func (m *SlurmMaintenance_windowRequestBuilder) WithUrl(rawUrl string) *SlurmMaintenance_windowRequestBuilder {
	return NewSlurmMaintenance_windowRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
