// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// SlurmRequestBuilder builds and executes requests for operations under \v1\slurm
type SlurmRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// Checkpoint the checkpoint property
// returns a *SlurmCheckpointRequestBuilder when successful
func (m *SlurmRequestBuilder) Checkpoint() *SlurmCheckpointRequestBuilder {
	return NewSlurmCheckpointRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Checkpoints the checkpoints property
// returns a *SlurmCheckpointsRequestBuilder when successful
func (m *SlurmRequestBuilder) Checkpoints() *SlurmCheckpointsRequestBuilder {
	return NewSlurmCheckpointsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Clusters the clusters property
// returns a *SlurmClustersRequestBuilder when successful
func (m *SlurmRequestBuilder) Clusters() *SlurmClustersRequestBuilder {
	return NewSlurmClustersRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// NewSlurmRequestBuilderInternal instantiates a new SlurmRequestBuilder and sets the default values.
func NewSlurmRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *SlurmRequestBuilder {
	m := &SlurmRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/slurm", pathParameters),
	}
	return m
}

// NewSlurmRequestBuilder instantiates a new SlurmRequestBuilder and sets the default values.
func NewSlurmRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *SlurmRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewSlurmRequestBuilderInternal(urlParams, requestAdapter)
}

// Events the events property
// returns a *SlurmEventsRequestBuilder when successful
func (m *SlurmRequestBuilder) Events() *SlurmEventsRequestBuilder {
	return NewSlurmEventsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Jobs the jobs property
// returns a *SlurmJobsRequestBuilder when successful
func (m *SlurmRequestBuilder) Jobs() *SlurmJobsRequestBuilder {
	return NewSlurmJobsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Maintenance_window the maintenance_window property
// returns a *SlurmMaintenance_windowRequestBuilder when successful
func (m *SlurmRequestBuilder) Maintenance_window() *SlurmMaintenance_windowRequestBuilder {
	return NewSlurmMaintenance_windowRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Nodes the nodes property
// returns a *SlurmNodesRequestBuilder when successful
func (m *SlurmRequestBuilder) Nodes() *SlurmNodesRequestBuilder {
	return NewSlurmNodesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Partitions the partitions property
// returns a *SlurmPartitionsRequestBuilder when successful
func (m *SlurmRequestBuilder) Partitions() *SlurmPartitionsRequestBuilder {
	return NewSlurmPartitionsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Restore the restore property
// returns a *SlurmRestoreRequestBuilder when successful
func (m *SlurmRequestBuilder) Restore() *SlurmRestoreRequestBuilder {
	return NewSlurmRestoreRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
